// Auto-generated from cars.csv — do not edit manually.
interface MarkEntry { id: string; name: string }

const MARKS_DATA: MarkEntry[] = [
  { id: "212", name: "212" },
  { id: "ABARTH", name: "Abarth" },
  { id: "AC", name: "AC" },
  { id: "ACURA", name: "Acura" },
  { id: "ADAM", name: "Adam" },
  { id: "ADLER", name: "Adler" },
  { id: "AION", name: "Aion" },
  { id: "AISTALAND", name: "Aistaland" },
  { id: "AITO", name: "Aito" },
  { id: "AIWAYS", name: "Aiways" },
  { id: "AIXAM", name: "Aixam" },
  { id: "ALFA_ROMEO", name: "Alfa Romeo" },
  { id: "ALPINA", name: "Alpina" },
  { id: "ALPINE", name: "Alpine" },
  { id: "AMBERAUTO", name: "Амберавто" },
  { id: "AMBERTRUCK", name: "Ambertruck" },
  { id: "AMC", name: "AMC" },
  { id: "AM_GENERAL", name: "AM General" },
  { id: "APAL", name: "Apal" },
  { id: "ARCFOX", name: "Arcfox" },
  { id: "ARIEL", name: "Ariel" },
  { id: "ARO", name: "Aro" },
  { id: "ASIA", name: "Asia" },
  { id: "ASTON_MARTIN", name: "Aston Martin" },
  { id: "ATOM", name: "Атом" },
  { id: "AUBURN", name: "Auburn" },
  { id: "AUDI", name: "Audi" },
  { id: "AURUS", name: "Aurus" },
  { id: "AUSTIN", name: "Austin" },
  { id: "AUSTIN_HEALEY", name: "Austin Healey" },
  { id: "AUTOBIANCHI", name: "Autobianchi" },
  { id: "AUTO_UNION", name: "Auto Union" },
  { id: "AVATR", name: "Avatr" },
  { id: "AVTOKAM", name: "Автокам" },
  { id: "BAIC", name: "BAIC" },
  { id: "BAJAJ", name: "Bajaj" },
  { id: "BALTIJAS_DZIPS", name: "Baltijas Dzips" },
  { id: "BAOJUN", name: "Baojun" },
  { id: "BATMOBILE", name: "Batmobile" },
  { id: "BAW", name: "BAW" },
  { id: "BELGEE", name: "Belgee" },
  { id: "BENTLEY", name: "Bentley" },
  { id: "BERTONE", name: "Bertone" },
  { id: "BESTUNE", name: "Bestune" },
  { id: "BILENKIN", name: "Bilenkin" },
  { id: "BIO_AUTO", name: "Bio Auto" },
  { id: "BITTER", name: "Bitter" },
  { id: "BIZZARRINI", name: "Bizzarrini" },
  { id: "BLAVAL", name: "Blaval" },
  { id: "BMW", name: "BMW" },
  { id: "BORGWARD", name: "Borgward" },
  { id: "BRABUS", name: "Brabus" },
  { id: "BRILLIANCE", name: "Brilliance" },
  { id: "BRISTOL", name: "Bristol" },
  { id: "BUFORI", name: "Bufori" },
  { id: "BUGATTI", name: "Bugatti" },
  { id: "BUICK", name: "Buick" },
  { id: "BYD", name: "BYD" },
  { id: "BYVIN", name: "Byvin" },
  { id: "CADILLAC", name: "Cadillac" },
  { id: "CALLAWAY", name: "Callaway" },
  { id: "CARBODIES", name: "Carbodies" },
  { id: "CATERHAM", name: "Caterham" },
  { id: "CHANA", name: "Chana" },
  { id: "CHANGAN", name: "Changan" },
  { id: "CHANGFENG", name: "Changfeng" },
  { id: "CHANGHE", name: "Changhe" },
  { id: "CHERY", name: "Chery" },
  { id: "CHERYEXEED", name: "Exeed" },
  { id: "CHEVROLET", name: "Chevrolet" },
  { id: "CHRYSLER", name: "Chrysler" },
  { id: "CIIMO", name: "Ciimo (Dongfeng-Honda)" },
  { id: "CITROEN", name: "Citroen" },
  { id: "CIZETA", name: "Cizeta" },
  { id: "CODA", name: "Coda" },
  { id: "COGGIOLA", name: "Coggiola" },
  { id: "CORD", name: "Cord" },
  { id: "COWIN", name: "Cowin" },
  { id: "CUPRA", name: "Cupra" },
  { id: "CZINGER", name: "Czinger" },
  { id: "DACIA", name: "Dacia" },
  { id: "DADI", name: "Dadi" },
  { id: "DAEWOO", name: "Daewoo" },
  { id: "DAIHATSU", name: "Daihatsu" },
  { id: "DAIMLER", name: "Daimler" },
  { id: "DALLARA", name: "Dallara" },
  { id: "DATSUN", name: "Datsun" },
  { id: "DAYUN", name: "Dayun" },
  { id: "DECO_RIDES", name: "Deco Rides" },
  { id: "DELAGE", name: "Delage" },
  { id: "DELOREAN", name: "DeLorean" },
  { id: "DENZA", name: "Denza" },
  { id: "DERWAYS", name: "Derways" },
  { id: "DESOTO", name: "DeSoto" },
  { id: "DE_TOMASO", name: "De Tomaso" },
  { id: "DKW", name: "DKW" },
  { id: "DODGE", name: "Dodge" },
  { id: "DONGFENG", name: "Dongfeng" },
  { id: "DONINVEST", name: "Doninvest" },
  { id: "DONKERVOORT", name: "Donkervoort" },
  { id: "DR", name: "DR" },
  { id: "DS", name: "DS" },
  { id: "DW_HOWER", name: "DW Hower" },
  { id: "EAGLE", name: "Eagle" },
  { id: "EAGLE_CARS", name: "Eagle Cars" },
  { id: "EDSEL", name: "Edsel" },
  { id: "ENOVATE", name: "Enovate (Enoreve)" },
  { id: "EONYX", name: "Eonyx" },
  { id: "ESTEO", name: "Esteo" },
  { id: "EVERUS", name: "Everus" },
  { id: "EVOLUTE", name: "Evolute" },
  { id: "EXCALIBUR", name: "Excalibur" },
  { id: "E_CAR", name: "E-Car" },
  { id: "E_MOBIL", name: "Ё-мобиль" },
  { id: "FACEL_VEGA", name: "Facel Vega" },
  { id: "FAW", name: "FAW" },
  { id: "FERRARI", name: "Ferrari" },
  { id: "FIAT", name: "Fiat" },
  { id: "FISKER", name: "Fisker" },
  { id: "FLANKER", name: "Flanker" },
  { id: "FORD", name: "Ford" },
  { id: "FORTHING", name: "Forthing" },
  { id: "FOTON", name: "Foton" },
  { id: "FRANKLIN", name: "Franklin" },
  { id: "FSO", name: "FSO" },
  { id: "FSR", name: "FSR" },
  { id: "FUQI", name: "Fuqi" },
  { id: "GAC", name: "GAC" },
  { id: "GAZ", name: "ГАЗ" },
  { id: "GEELY", name: "Geely" },
  { id: "GENESIS", name: "Genesis" },
  { id: "GEO", name: "Geo" },
  { id: "GMA", name: "GMA" },
  { id: "GMC", name: "GMC" },
  { id: "GOGGOMOBIL", name: "Goggomobil" },
  { id: "GONOW", name: "Gonow" },
  { id: "GORDON", name: "Gordon" },
  { id: "GP", name: "GP" },
  { id: "GREAT_WALL", name: "Great Wall" },
  { id: "GUMPERT", name: "Gumpert" },
  { id: "HAFEI", name: "Hafei" },
  { id: "HAIMA", name: "Haima" },
  { id: "HANOMAG", name: "Hanomag" },
  { id: "HANTENG", name: "Hanteng" },
  { id: "HAVAL", name: "Haval" },
  { id: "HAWTAI", name: "Hawtai" },
  { id: "HEDMOS", name: "Hedmos" },
  { id: "HEINKEL", name: "Heinkel" },
  { id: "HENGTIAN", name: "Hengtian" },
  { id: "HENNESSEY", name: "Hennessey" },
  { id: "HINDUSTAN", name: "Hindustan" },
  { id: "HIPHI", name: "HiPhi" },
  { id: "HISPANO_SUIZA", name: "Hispano-Suiza" },
  { id: "HOLDEN", name: "Holden" },
  { id: "HONDA", name: "Honda" },
  { id: "HONGQI", name: "Hongqi" },
  { id: "HORCH", name: "Horch" },
  { id: "HOZON", name: "Hozon" },
  { id: "HSV", name: "HSV" },
  { id: "HUAIHAI_HOANN", name: "Huaihai (Hoann)" },
  { id: "HUANGHAI", name: "HuangHai" },
  { id: "HUAZI", name: "Huazi" },
  { id: "HUDSON", name: "Hudson" },
  { id: "HUMBER", name: "Humber" },
  { id: "HUMMER", name: "Hummer" },
  { id: "HYCAN", name: "Hycan" },
  { id: "HYPERION", name: "Hyperion" },
  { id: "HYUNDAI", name: "Hyundai" },
  { id: "ICAR", name: "iCar" },
  { id: "ICAUR", name: "iCaur" },
  { id: "IG", name: "Иж" },
  { id: "IM_MOTORS", name: "IM Motors (Zhiji)" },
  { id: "INEOS", name: "Ineos" },
  { id: "INFINITI", name: "Infiniti" },
  { id: "INNOCENTI", name: "Innocenti" },
  { id: "INTERNATIONAL", name: "International Harvester" },
  { id: "INVICTA", name: "Invicta" },
  { id: "IRAN_KHODRO", name: "Iran Khodro" },
  { id: "ISDERA", name: "Isdera" },
  { id: "ISUZU", name: "Isuzu" },
  { id: "IVECO", name: "Iveco" },
  { id: "JAC", name: "JAC" },
  { id: "JAECOO", name: "Jaecoo" },
  { id: "JAGUAR", name: "Jaguar" },
  { id: "JEEP", name: "Jeep" },
  { id: "JELAND", name: "Jeland" },
  { id: "JENSEN", name: "Jensen" },
  { id: "JETOUR", name: "JETOUR" },
  { id: "JETTA", name: "Jetta" },
  { id: "JIANGNAN", name: "Jiangnan" },
  { id: "JIDU", name: "Jidu" },
  { id: "JINBEI", name: "Jinbei" },
  { id: "JMC", name: "JMC" },
  { id: "JMEV", name: "JMEV" },
  { id: "JONWAY", name: "Jonway" },
  { id: "KAIYI", name: "Kaiyi" },
  { id: "KANONIR", name: "Канонир" },
  { id: "KARMA", name: "Karma" },
  { id: "KAWEI", name: "Kawei" },
  { id: "KGM", name: "KGM" },
  { id: "KIA", name: "Kia" },
  { id: "KNEWSTAR", name: "Knewstar" },
  { id: "KOENIGSEGG", name: "Koenigsegg" },
  { id: "KOMBAT", name: "Комбат" },
  { id: "KTM", name: "KTM AG" },
  { id: "KYC", name: "KYC" },
  { id: "LAMBORGHINI", name: "Lamborghini" },
  { id: "LANCIA", name: "Lancia" },
  { id: "LANDWIND", name: "Landwind" },
  { id: "LAND_ROVER", name: "Land Rover" },
  { id: "LEAPMOTOR", name: "Leapmotor" },
  { id: "LETIN", name: "Letin" },
  { id: "LEVC", name: "LEVC" },
  { id: "LEXUS", name: "Lexus" },
  { id: "LIEBAO", name: "Liebao Motor" },
  { id: "LIFAN", name: "Lifan" },
  { id: "LIGIER", name: "Ligier" },
  { id: "LINCOLN", name: "Lincoln" },
  { id: "LINGXI", name: "Lingxi" },
  { id: "LIVAN", name: "Livan" },
  { id: "LIXIANG", name: "Li Auto (Lixiang)" },
  { id: "LOGEM", name: "Logem" },
  { id: "LOTUS", name: "Lotus" },
  { id: "LTI", name: "LTI" },
  { id: "LUAZ", name: "ЛуАЗ" },
  { id: "LUCID", name: "Lucid" },
  { id: "LUXEED", name: "Luxeed" },
  { id: "LUXGEN", name: "Luxgen" },
  { id: "LYNK_CO", name: "Lynk & Co" },
  { id: "MAEXTRO", name: "Maextro" },
  { id: "MAHINDRA", name: "Mahindra" },
  { id: "MAPLE", name: "Maple" },
  { id: "MARCOS", name: "Marcos" },
  { id: "MARLIN", name: "Marlin" },
  { id: "MARUSSIA", name: "Marussia" },
  { id: "MARUTI", name: "Maruti" },
  { id: "MASERATI", name: "Maserati" },
  { id: "MATRA", name: "Matra" },
  { id: "MAXUS", name: "Maxus" },
  { id: "MAYBACH", name: "Maybach" },
  { id: "MAZDA", name: "Mazda" },
  { id: "MCLAREN", name: "McLaren" },
  { id: "MEGA", name: "Mega" },
  { id: "MERCEDES", name: "Mercedes-Benz" },
  { id: "MERCURY", name: "Mercury" },
  { id: "MERKUR", name: "Merkur" },
  { id: "MESSERSCHMITT", name: "Messerschmitt" },
  { id: "METROCAB", name: "Metrocab" },
  { id: "MG", name: "MG" },
  { id: "MIA", name: "Mia" },
  { id: "MICRO", name: "Micro" },
  { id: "MICROCAR", name: "Microcar" },
  { id: "MINELLI", name: "Minelli" },
  { id: "MINI", name: "Mini" },
  { id: "MITSUBISHI", name: "Mitsubishi" },
  { id: "MITSUOKA", name: "Mitsuoka" },
  { id: "MOBILIZE", name: "Mobilize" },
  { id: "MORGAN", name: "Morgan" },
  { id: "MORRIS", name: "Morris" },
  { id: "MOSCVICH", name: "Москвич" },
  { id: "M_HERO", name: "M-Hero" },
  { id: "NASH", name: "Nash" },
  { id: "NIO", name: "Nio" },
  { id: "NISSAN", name: "Nissan" },
  { id: "NOBLE", name: "Noble" },
  { id: "NORDCROSS", name: "Nordcross" },
  { id: "OLDSMOBILE", name: "Oldsmobile" },
  { id: "OLTCIT", name: "Oltcit" },
  { id: "OMODA", name: "Omoda" },
  { id: "OPEL", name: "Opel" },
  { id: "ORA", name: "Ora" },
  { id: "ORANGE", name: "Orange" },
  { id: "OSCA", name: "Osca" },
  { id: "OSHAN", name: "Oshan" },
  { id: "OTING", name: "Oting" },
  { id: "OVERLAND", name: "Overland" },
  { id: "PACKARD", name: "Packard" },
  { id: "PAGANI", name: "Pagani" },
  { id: "PANOZ", name: "Panoz" },
  { id: "PERODUA", name: "Perodua" },
  { id: "PEUGEOT", name: "Peugeot" },
  { id: "PGO", name: "PGO" },
  { id: "PIAGGIO", name: "Piaggio" },
  { id: "PIERCE_ARROW", name: "Pierce-Arrow" },
  { id: "PLYMOUTH", name: "Plymouth" },
  { id: "POLAR_STONE_JISHI", name: "Polar Stone (Jishi)" },
  { id: "POLESTAR", name: "Polestar" },
  { id: "PONTIAC", name: "Pontiac" },
  { id: "PORSCHE", name: "Porsche" },
  { id: "PREMIER", name: "Premier" },
  { id: "PROMO_AUTO", name: "Спортивные авто и реплики" },
  { id: "PROTON", name: "Proton" },
  { id: "PUCH", name: "Puch" },
  { id: "PUMA", name: "Puma" },
  { id: "PUNK", name: "Punk" },
  { id: "QIANTU", name: "Qiantu" },
  { id: "QINGLING", name: "Qingling" },
  { id: "QOROS", name: "Qoros" },
  { id: "QVALE", name: "Qvale" },
  { id: "RADAR", name: "Radar" },
  { id: "RADFORD", name: "Radford" },
  { id: "RAM", name: "Ram" },
  { id: "RAVON", name: "Ravon" },
  { id: "RAYTON_FISSORE", name: "Rayton Fissore" },
  { id: "RELIANT", name: "Reliant" },
  { id: "RENAISSANCE_CARS", name: "Renaissance" },
  { id: "RENAULT", name: "Renault" },
  { id: "REZVANI", name: "Rezvani" },
  { id: "RIMAC", name: "Rimac" },
  { id: "RINSPEED", name: "Rinspeed" },
  { id: "RISING_AUTO", name: "Rising Auto" },
  { id: "RIVIAN", name: "Rivian" },
  { id: "ROEWE", name: "Roewe" },
  { id: "ROLLS_ROYCE", name: "Rolls-Royce" },
  { id: "RONART", name: "Ronart" },
  { id: "ROSSA", name: "Rossa" },
  { id: "ROVER", name: "Rover" },
  { id: "ROX", name: "Rox" },
  { id: "RUSSO_BALTIQUE", name: "Руссо-Балт" },
  { id: "SAAB", name: "Saab" },
  { id: "SAIC", name: "SAIC" },
  { id: "SAIPA", name: "Saipa" },
  { id: "SALEEN", name: "Saleen" },
  { id: "SAMSUNG", name: "Renault Samsung" },
  { id: "SANDSTORM", name: "Sandstorm" },
  { id: "SANTANA", name: "Santana" },
  { id: "SATURN", name: "Saturn" },
  { id: "SCION", name: "Scion" },
  { id: "SCOUT", name: "Scout" },
  { id: "SEARS", name: "Sears" },
  { id: "SEAT", name: "SEAT" },
  { id: "SENAT", name: "Senat" },
  { id: "SERES", name: "Seres" },
  { id: "SHANGHAI_MAPLE", name: "Shanghai Maple" },
  { id: "SHUANGHUAN", name: "ShuangHuan" },
  { id: "SIMCA", name: "Simca" },
  { id: "SKM", name: "SKM" },
  { id: "SKODA", name: "Skoda" },
  { id: "SKYWELL", name: "Skywell" },
  { id: "SKYWORTH", name: "Skyworth" },
  { id: "SMART", name: "Smart" },
  { id: "SMZ", name: "СМЗ" },
  { id: "SOLARIS", name: "Solaris" },
  { id: "SOLLERS", name: "Sollers" },
  { id: "SOUEAST", name: "Soueast" },
  { id: "SPECTRE", name: "Spectre" },
  { id: "SPYKER", name: "Spyker" },
  { id: "SSANG_YONG", name: "SsangYong" },
  { id: "START", name: "Старт" },
  { id: "STELATO", name: "Stelato" },
  { id: "STEYR", name: "Steyr" },
  { id: "STUDEBAKER", name: "Studebaker" },
  { id: "SUBARU", name: "Subaru" },
  { id: "SUZUKI", name: "Suzuki" },
  { id: "SWM", name: "SWM" },
  { id: "TAGAZ", name: "ТагАЗ" },
  { id: "TALBOT", name: "Talbot" },
  { id: "TANK", name: "Tank" },
  { id: "TATA", name: "Tata" },
  { id: "TATRA", name: "Tatra" },
  { id: "TAZZARI", name: "Tazzari" },
  { id: "TENET", name: "Tenet" },
  { id: "TENET_PLUS", name: "Tenet Plus" },
  { id: "TESLA", name: "Tesla" },
  { id: "THAIRUNG", name: "Thairung" },
  { id: "THINK", name: "Think" },
  { id: "TIANMA", name: "Tianma" },
  { id: "TIANYE", name: "Tianye" },
  { id: "TOFAS", name: "Tofas" },
  { id: "TOYOTA", name: "Toyota" },
  { id: "TRABANT", name: "Trabant" },
  { id: "TRAMONTANA", name: "Tramontana" },
  { id: "TRIUMPH", name: "Triumph" },
  { id: "TRUMPCHI", name: "GAC Trumpchi" },
  { id: "TVR", name: "TVR" },
  { id: "UAZ", name: "УАЗ" },
  { id: "ULTIMA", name: "Ultima" },
  { id: "UMO", name: "UMO" },
  { id: "VAUXHALL", name: "Vauxhall" },
  { id: "VAZ", name: "Lada (ВАЗ)" },
  { id: "VECTOR", name: "Vector" },
  { id: "VENTURI", name: "Venturi" },
  { id: "VENUCIA", name: "Venucia" },
  { id: "VGV", name: "VGV" },
  { id: "VINFAST", name: "VinFast" },
  { id: "VOLGA", name: "Volga" },
  { id: "VOLKSWAGEN", name: "Volkswagen" },
  { id: "VOLVO", name: "Volvo" },
  { id: "VORTEX", name: "Vortex" },
  { id: "VOYAH", name: "Voyah" },
  { id: "VUHL", name: "VUHL" },
  { id: "WANDERER", name: "Wanderer" },
  { id: "WARTBURG", name: "Wartburg" },
  { id: "WELTMEISTER", name: "Weltmeister" },
  { id: "WESTFIELD", name: "Westfield" },
  { id: "WEY", name: "Wey" },
  { id: "WIESMANN", name: "Wiesmann" },
  { id: "WILLIS", name: "Willys" },
  { id: "WULING", name: "Wuling" },
  { id: "W_MOTORS", name: "W Motors" },
  { id: "XCITE", name: "Xcite" },
  { id: "XEV", name: "XEV" },
  { id: "XIAOMI", name: "Xiaomi" },
  { id: "XINKAI", name: "Xin Kai" },
  { id: "XPENG", name: "Xpeng" },
  { id: "YANDEX_ROVER", name: "Яндекс Ровер" },
  { id: "YEMA", name: "Yema" },
  { id: "YIPAI", name: "Yipai" },
  { id: "YUDO", name: "Yudo" },
  { id: "YULON", name: "Yulon" },
  { id: "ZASTAVA", name: "Zastava" },
  { id: "ZAZ", name: "ЗАЗ" },
  { id: "ZEEKR", name: "Zeekr" },
  { id: "ZENOS", name: "Zenos" },
  { id: "ZENVO", name: "Zenvo" },
  { id: "ZHIDO", name: "Zhido" },
  { id: "ZIBAR", name: "Zibar" },
  { id: "ZIL", name: "ЗИЛ" },
  { id: "ZIS", name: "ЗиС" },
  { id: "ZOTYE", name: "Zotye" },
  { id: "ZUBR", name: "Zubr" },
  { id: "ZX", name: "ZX" },
];

const MODELS_BY_MARK_ID: Record<string, string[]> = {
  ["212"]: ["T01", "T10", "Explorer 01"],
  ["ABARTH"]: ["124 Spider", "500", "595", "600e", "695", "Fastback", "Pulse"],
  ["AC"]: ["378 GT Zagato", "Ace", "Aceca", "Cobra", "Cobra GT"],
  ["ACURA"]: ["ADX", "CDX", "CL", "CSX", "EL", "ILX", "Integra", "Legend", "MDX", "NSX", "RDX", "RL", "RLX", "RSX", "SLX", "TL", "TLX", "TSX", "ZDX"],
  ["ADAM"]: ["Revo"],
  ["ADLER"]: ["Diplomat", "Trumpf Junior"],
  ["AION"]: ["Hyptec GT (Hyper GT)", "Hyptec HT (Hyper HT)", "Hyptec SSR (Hyper SSR)", "Hyptec A800", "Hyptec HL", "Hyptec S600", "I60", "LX", "LX Plus", "N60", "RT", "S", "S Plus", "UT", "V", "V Plus", "Y", "Y Plus"],
  ["AISTALAND"]: ["GT7"],
  ["AITO"]: ["M5", "M6", "M7", "M8", "M9"],
  ["AIWAYS"]: ["U5", "U6"],
  ["AIXAM"]: ["500"],
  ["ALFA_ROMEO"]: ["105/115", "145", "146", "147", "155", "156", "159", "164", "166", "1900", "2600", "33", "33 Stradale", "4C", "6", "6C", "75", "8C Competizione", "90", "Alfasud", "Alfetta", "Arna", "Brera", "Disco Volante", "Giulia", "Giulietta", "GT", "GTA Coupe", "GTV", "Junior", "MiTo", "Montreal", "RZ", "Spider", "Sprint", "Stelvio", "SZ", "Tonale"],
  ["ALPINA"]: ["B10", "B11", "B12", "B3", "B4", "B5", "B6", "B7", "B8", "B9", "C1", "C2", "D10", "D3", "D4", "D5", "Roadster", "XB7", "XD3", "XD4"],
  ["ALPINE"]: ["A110", "A290", "A310", "A390", "A610", "GTA"],
  ["AMBERAUTO"]: ["А5"],
  ["AMBERTRUCK"]: ["Work"],
  ["AMC"]: ["Eagle", "Gremlin", "Hornet", "Matador", "Rambler Ambassador", "Rambler Classic"],
  ["AM_GENERAL"]: ["HMMWV (Humvee)"],
  ["APAL"]: ["21541 Stalker"],
  ["ARCFOX"]: ["Alpha S", "Alpha S5", "Alpha S6", "Alpha T", "Alpha T5", "Alpha T6", "Beta T1", "Kaola", "Lite", "S3", "T1", "Wendao V9"],
  ["ARIEL"]: ["Atom", "Nomad"],
  ["ARO"]: ["10", "24"],
  ["ASIA"]: ["Retona", "Rocsta", "Topic", "Towner"],
  ["ASTON_MARTIN"]: ["Bulldog", "Cygnet", "DB11", "DB12", "DB5", "DB6", "DB7", "DB9", "DBS", "DBX", "DB AR1", "Lagonda", "Lagonda Taraf", "One-77", "Rapide", "Tickford Capri", "Vanquish", "V12 Speedster", "V12 Vantage", "V12 Zagato", "V8 Vantage", "V8 Zagato", "Valhalla", "Valiant", "Valkyrie", "Valour", "Vanquish Zagato", "Virage", "Vulcan"],
  ["ATOM"]: ["01"],
  ["AUBURN"]: ["Speedster"],
  ["AUDI"]: ["100", "200", "50", "60", "80", "90", "920", "A1", "A2", "A3", "A4", "A4 allroad", "A5", "A6", "A6 e-tron", "A7", "A8", "A6 allroad", "Cabriolet", "Coupe", "E5", "E7X", "e-tron", "e-tron GT", "e-tron S", "e-tron Sportback", "e-tron S Sportback", "Front", "NSU RO 80", "Nuvolari", "Q2", "Q3", "Q3 Sportback", "Q4 e-tron", "Q4 Sportback e-tron", "Q5", "Q5 e-tron", "Q5 Sportback", "Q6", "Q6 e-tron", "Q6 Sportback e-tron", "Q7", "Q8", "Q8 e-tron", "Q8 Sportback e-tron", "Quattro", "R8", "R8 LMP", "RS 2", "RS 3", "RS 4", "RS 5", "RS 6", "RS 7", "RS Q3", "RS e-tron GT", "RS Q3 Sportback", "RS Q8", "S1", "S2", "S3", "S4", "S5", "S6", "S6 e-tron", "S7", "S8", "SQ2", "SQ5", "SQ5 Sportback", "SQ6 e-tron", "SQ6 Sportback e-tron", "SQ7", "SQ8", "SQ8 e-tron", "SQ8 Sportback e-tron", "S e-tron GT", "TT", "TTS", "TT RS", "Typ R", "V8"],
  ["AURUS"]: ["Komendant", "Lafet", "Senat"],
  ["AUSTIN"]: ["Allegro", "Ambassador", "FL2", "FX4", "Maestro", "Maxi", "Metro", "Mini", "Montego", "Princess", "Sprite"],
  ["AUSTIN_HEALEY"]: ["100", "3000"],
  ["AUTOBIANCHI"]: ["A 112"],
  ["AUTO_UNION"]: ["1000 Sp"],
  ["AVATR"]: ["06", "07", "11", "12"],
  ["AVTOKAM"]: ["2160", "2163", "3101"],
  ["BAIC"]: ["A1", "BJ2021", "BJ2025F", "BJ2030", "BJ30", "BJ40", "BJ41", "BJ60", "BJ80", "BJ90", "BJ2020", "BJ2026", "BJ212", "EC3", "EU", "EU5", "EU5 Plus", "EU7", "EU8", "EX3", "EX5", "Jeep 2500", "Kenbo 600", "Luba (XB624)", "Ruixiang X3", "Ruixiang X5", "U5", "U5 Plus", "U7", "X3", "X35", "X5", "X55", "X7", "X75"],
  ["BAJAJ"]: ["Qute"],
  ["BALTIJAS_DZIPS"]: ["BD-1322"],
  ["BAOJUN"]: ["310", "360", "510", "530", "730", "E100", "E200", "E300", "Kiwi EV", "RC-5", "RC-6", "RM-5", "RS-3", "RS-5", "RS-7", "Valli", "Xiangjing", "Yep", "Yep Plus", "Yunduo", "Yunhai"],
  ["BATMOBILE"]: ["1989", "2018"],
  ["BAW"]: ["212", "Ace M7", "Calorie F7", "Jiabao", "M8", "MPV", "Pony (Yuanbao)"],
  ["BELGEE"]: ["S50", "X50", "X50+", "X70", "X80"],
  ["BENTLEY"]: ["Arnage", "Azure", "Bentayga", "Brooklands", "Continental", "Continental Flying Spur", "Continental GT", "Eight", "Flying Spur", "Mark VI", "Mulliner Bacalar", "Mulliner Batur", "Mulsanne", "R Type", "S", "Turbo R", "T-Series"],
  ["BERTONE"]: ["Freeclimber"],
  ["BESTUNE"]: ["B70", "T55", "T77", "T90"],
  ["BILENKIN"]: ["Vintage"],
  ["BIO_AUTO"]: ["evA-4"],
  ["BITTER"]: ["CD", "Type 3"],
  ["BIZZARRINI"]: ["5300 GT"],
  ["BLAVAL"]: ["FH-EQ"],
  ["BMW"]: ["02 (E10)", "1 серии", "1M", "2 серии Active Tourer", "2 серии", "2 серии Gran Tourer", "315", "320", "3200", "321", "326", "327", "340", "3 серии", "3/15", "4 серии", "501", "502", "503", "507", "5 серии", "600", "6 серии", "700", "7 серии", "8 серии", "E3", "E9", "i3", "i4", "i5", "i7", "i8", "Isetta", "iX", "iX1", "iX2", "iX3", "iX5", "M2", "M3", "M4", "M5", "M6", "M8", "M1", "Nazca", "New Class", "X1", "X2", "X3", "X3 M", "X4", "X4 M", "X5", "X5 M", "X6", "X6 M", "X7", "XM", "Z1", "Z3", "Z3 M", "Z4", "Z4 M", "Z8"],
  ["BORGWARD"]: ["2000", "BX5", "Hansa 1100"],
  ["BRABUS"]: ["7.3S", "Bodo", "Crawler", "E V12", "G V12", "ML 63 Biturbo", "M V12", "Rocket GTS", "SV12"],
  ["BRILLIANCE"]: ["FRV (BS2)", "H230", "H530", "M1 (BS6)", "M2 (BS4)", "M3 (BC3)", "V3", "V5"],
  ["BRISTOL"]: ["Blenheim", "Blenheim Speedster", "Fighter"],
  ["BUFORI"]: ["Geneva", "La Joya"],
  ["BUGATTI"]: ["Bolide", "Centodieci", "Chiron", "Divo", "EB 110", "EB 112", "EB Veyron 16.4", "F.K.P. Hommage", "Tourbillon", "Type 55", "W16 Mistral"],
  ["BUICK"]: ["Cascada", "Century", "Electra", "Electra E4", "Electra E5", "Electra E7", "Electra L7", "Enclave", "Encore", "Encore GX", "Encore Plus", "Envision", "Envista", "Estate Wagon", "Excelle", "GL6", "GL8", "GS", "LaCrosse", "LeSabre", "Limited", "Lucerne", "Park Avenue", "Rainier", "Reatta", "Regal", "Rendezvous", "Riviera", "Roadmaster", "Skyhawk", "Skylark", "Special", "Super", "Terraza", "Velite 5", "Velite 6", "Velite 7", "Verano", "Wildcat"],
  ["BYD"]: ["Atto 2", "Chazor", "D1", "Datang", "Destroyer 05", "Dolphin", "Dolphin G", "E1", "E2", "E3", "E5", "E6", "E7", "E9", "F0", "F3", "F5", "F6", "F8 (S8)", "FangChengBao Leopard 5", "FangChengBao Leopard 8", "FangChengBao Titanium 3", "FangChengBao Titanium 7", "Flyer", "Frigate 07", "G3", "G6", "Han", "Han L", "L3", "M6", "Qin", "Qin Max", "Racco", "S6", "Seagull", "Seal", "Seal 05", "Seal 06", "Seal 06 GT", "Seal 07", "Seal 08", "Sea Lion 05", "Sea Lion 06", "Sea Lion 07", "Sea Lion 08", "Shark (Shark 6)", "Song", "Song EV", "Song L", "Song Max", "Song Plus", "Song Pro", "Song Ultra", "Tang", "Tang L", "Xia (M9)", "Yangwang U7", "Yangwang U8", "Yangwang U9", "Yuan", "Yuan Plus", "Yuan Up"],
  ["BYVIN"]: ["BD132J (CoCo)", "BD326J (Moca)"],
  ["CADILLAC"]: ["Allante", "ATS", "ATS-V", "BLS", "Brougham", "Catera", "Celestiq", "CT4", "CT4-V", "CT5", "CT5-V", "CT6", "CTS", "CTS-V", "DeVille", "DTS", "Eldorado", "ELR", "Escalade", "Escalade iQ", "Escalade-V", "Fleetwood", "GT4", "Lyriq-V", "LSE", "Lyriq", "Model 30", "Optiq", "Optiq-V", "Series 314", "Series 341", "Series 62", "Seville", "Sixty Special", "SRX", "STS", "STS-V", "V12", "Vistiq", "XLR", "XT4", "XT5", "XT6", "XTS"],
  ["CALLAWAY"]: ["C12"],
  ["CARBODIES"]: ["FX4"],
  ["CATERHAM"]: ["21", "CSR", "Seven"],
  ["CHANA"]: ["Benni", "SC6390", "Taurustar"],
  ["CHANGAN"]: ["Qiyuan A05", "Qiyuan A06", "Qiyuan A07", "Alsvin", "Alsvin V7", "Auchan A600", "Auchan A600 EV", "Auchan Changxing", "Benben E-Star", "Benni", "Benni EC/EV", "CM-8", "CS15", "CS35", "CS35 Max", "CS35 Plus", "CS55", "CS55 Plus", "CS75", "CS75 Plus", "CS75 Pro", "CS85", "CS95", "CS95 Plus", "CX20", "Oshan CX70", "Qiyuan E07", "Eado", "Eado DT", "Eado Plus", "Lantuozhe (Explorer)", "Deepal G318", "Hunter", "Qiyuan Hunter K50", "Hunter Plus", "Kaicene F70", "Deepal L06", "Deepal L07", "Lamore", "Linmax", "Lumin", "Oushan Changxing", "Qiyuan Q05", "Qiyuan Q06", "Qiyuan Q07", "Raeton", "Raeton CC", "Raeton Plus", "Deepal S05", "Deepal S07 (S7)", "Deepal S09", "Deepal SL03", "UNI-K", "UNI-L", "UNI-S (CS55 Plus)", "UNI-T", "UNI-V", "UNI-Z", "X5 Plus", "X7 Plus", "Yida", "Z-Shine"],
  ["CHANGFENG"]: ["SUV (CS6)", "Flying", "Liebao Leopard"],
  ["CHANGHE"]: ["Freedom", "Ideal"],
  ["CHERY"]: ["Amulet (A15)", "Arrizo 6", "Arrizo 7", "Arrizo 3", "Arrizo 5", "Arrizo 5 GT", "Arrizo 5 Plus", "Arrizo 8", "Arrizo 8 Pro", "B13", "Bonus (A13)", "Bonus 3 (E3/A19)", "CrossEastar (B14)", "Domi", "E5", "eQ1", "eQ5", "eQ7", "Explore 06", "Face", "Fora (A21)", "Fulwin A8", "Fulwin A9L", "Fulwin T10", "Fulwin T11", "Fulwin T6", "Fulwin T8", "Fulwin T9", "Fulwin T9L", "Fulwin X3", "IndiS (S18D)", "Karry", "Kimo (A1)", "M11 (A3)", "Omoda 5", "Oriental Son (B11)", "Q22", "Sweet (QQ)", "QQ3", "QQ6 (S21)", "QQme", "QQ Ice Cream", "Rely R08", "Tiggo (T11)", "Tiggo 2", "Tiggo 2 Pro", "Tiggo 3", "Tiggo 3x", "Tiggo 3xe", "Tiggo 4", "Tiggo 4 Pro", "Tiggo 5", "Tiggo 5x", "Tiggo 7", "Tiggo 7L", "Tiggo 7 Plus", "Tiggo 7 Pro", "Tiggo 7 Pro Max", "Tiggo 7 Pro Plug-in Hybrid", "Tiggo 8", "Tiggo 8L", "Tiggo 8 Plus", "Tiggo 8 Pro", "Tiggo 8 Pro e+", "Tiggo 8 Pro Max", "Tiggo 8 Pro Plug-in Hybrid", "Tiggo 9", "Tiggo E", "Very (A13)", "Windcloud (A11)"],
  ["CHERYEXEED"]: ["Sterra ES", "ET5", "ET8", "EX7", "Exlantix ES", "Exlantix ET", "LX", "RX", "Sterra ET", "TX", "TXL", "VX", "Yaoguang"],
  ["CHEVROLET"]: ["3000-Series", "Alero", "Apache", "Astra", "Astro", "Avalanche", "Aveo", "Bel Air", "Beretta", "Blazer", "Blazer EV", "Bolt", "Bolt EUV", "Camaro", "Caprice", "Captiva", "Captiva Sport", "Cavalier", "Celebrity", "Celta", "Chevelle", "Chevette", "Citation", "C/K", "Classic", "Matiz", "Cobalt", "Colorado", "Corsa", "Corsica", "Corvair", "Corvette", "Cruze", "Cruze (HR)", "CSV CR8", "C-10", "Damas", "Deluxe", "El Camino", "Epica", "Equinox", "Equinox EV", "Evanda", "Express", "Fleetmaster", "Groove", "HHR", "Impala", "Blazer K5", "Kalos", "Lacetti", "Lanos", "Lumina", "Lumina APV", "LUV D-MAX", "Malibu", "Master", "Menlo", "Metro", "Monte Carlo", "Monza", "MW", "Nexia", "Niva", "Nova", "Nubira", "Omega", "Onix", "Orlando", "Prizm", "Rezzo", "Sail", "Seeker", "Silverado", "Sonic", "Spark", "Spark EUV", "Special DeLuxe", "Spin", "SS", "SSR", "Standard", "Starcraft", "Suburban", "S-10 Pickup", "Tacuma", "Tahoe", "Tavera", "Tracker", "TrailBlazer", "Trans Sport", "Traverse", "Trax", "Uplander", "Van", "Vectra", "Venture", "Viva", "Volt", "Zafira"],
  ["CHRYSLER"]: ["180", "200", "300", "300C", "300M", "300 Letter Series", "Aspen", "Cirrus", "Concorde", "Cordoba", "Crossfire", "Daytona", "Dynasty", "ES", "Fifth Avenue", "Imperial", "Imperial Crown", "Intrepid", "LeBaron", "LHS", "Nassau", "Neon", "Newport", "New Yorker", "Pacifica", "Prowler", "PT Cruiser", "Saratoga", "Sebring", "Six", "Stratus", "TC by Maserati", "Town & Country", "Viper", "Vision", "Voyager", "Windsor", "Ypsilon"],
  ["CIIMO"]: ["M-NV", "X-NV"],
  ["CITROEN"]: ["2 CV", "Ami", "Ami EV", "AX", "Basalt", "Berlingo", "BX", "C1", "C2", "C3", "C3L", "C3 Aircross", "C3 Picasso", "C3-XR", "C4", "C4 Aircross", "C4 Cactus", "C4 Picasso", "C4 SpaceTourer", "C5", "C5 Aircross", "C5 X", "C6", "C8", "CX", "C-Crosser", "C-Elysee", "C-Quatre", "C-Triomphe", "C-ZERO", "DS", "DS3", "DS4", "DS5", "Dyane", "Evasion", "E-Mehari", "GS", "Jumpy", "LN", "Nemo", "Saxo", "SM", "SpaceTourer", "Traction Avant", "Visa", "Xantia", "XM", "Xsara", "Xsara Picasso", "ZX"],
  ["CIZETA"]: ["V16t"],
  ["CODA"]: ["EV"],
  ["COGGIOLA"]: ["T Rex"],
  ["CORD"]: ["L-29"],
  ["COWIN"]: ["Showjet"],
  ["CUPRA"]: ["Ateca", "Born", "Formentor", "Leon", "Raval", "Tavascan", "Terramar"],
  ["CZINGER"]: ["21C"],
  ["DACIA"]: ["1300", "1310", "1410", "Bigster", "Dokker", "Duster", "Jogger", "Lodgy", "Logan", "Nova", "Pick-Up", "Sandero", "Solenza", "Spring", "SuperNova"],
  ["DADI"]: ["City Leading", "Shuttle", "Smoothing"],
  ["DAEWOO"]: ["Alpheon", "Arcadia", "Chairman", "Damas", "Espero", "Evanda", "G2X", "Gentra", "Kalos", "Korando", "Lacetti", "Lacetti Premiere", "Lanos", "Leganza", "LeMans", "Magnus", "Matiz", "Matiz Creative", "Musso", "Nexia", "Nubira", "Prince", "Racer", "Rezzo", "Royale", "Sens", "Tacuma", "Tico", "Tosca", "Winstorm"],
  ["DAIHATSU"]: ["Altis", "Applause", "Atrai", "Bee", "Be-go", "Boon", "Boon Luminas", "Cast", "Ceria", "Charade", "Charmant", "Coo", "Copen", "Cuore", "Delta Wagon", "Esse", "Extol", "Fellow", "Feroza", "Gran Move", "Hijet", "Hijet Caddie", "Leeza", "Materia", "MAX", "Mebius", "Midget", "Mira", "Mira Cocoa", "Mira e:S", "Mira Gino", "Mira Tocot", "Move", "Move Canbus", "Move Conte", "Move Latte", "Naked", "Opti", "Pyzar", "Rocky", "Rugger", "Sirion", "Sonica", "Storia", "Taft", "Tanto", "Tanto Exe", "Terios", "Thor", "Trevis", "Wake", "Wildcat", "Xenia", "YRV"],
  ["DAIMLER"]: ["DS420", "Regency", "Sovereign (XJ6)", "SP250", "XJ40", "XJS", "X300", "X308", "X350"],
  ["DALLARA"]: ["Stradale"],
  ["DATSUN"]: ["200/220/260/280C", "240Z", "280Z", "280ZX", "620", "720", "Bluebird", "Cherry", "GO", "GO+", "Laurel", "mi-DO", "on-DO", "Stanza", "Sunny", "Urvan", "Violet"],
  ["DAYUN"]: ["Pickup", "Yuanzhi M1", "Yuehu"],
  ["DECO_RIDES"]: ["Zephyr"],
  ["DELAGE"]: ["D12", "D6", "DI"],
  ["DELOREAN"]: ["DMC-12"],
  ["DENZA"]: ["500", "D9", "N7", "N8", "N8L", "N9", "X", "Z9"],
  ["DERWAYS"]: ["Antelope", "Aurora", "Cowboy", "Land Crown", "Plutus", "Saladin", "Shuttle"],
  ["DESOTO"]: ["Custom", "Deluxe", "Firedome", "Fireflite"],
  ["DE_TOMASO"]: ["Bigua", "Guara", "Longchamp", "Mangusta", "Pantera", "Vallelunga"],
  ["DKW"]: ["3=6"],
  ["DODGE"]: ["600", "Aries", "Avenger", "Caliber", "Caravan", "Challenger", "Charger", "Charger Daytona", "Colt", "Coronet", "Custom Royal", "D8", "Dakota", "Dart", "Daytona", "Diplomat", "Durango", "D/W Series", "Dynasty", "Hornet", "Intrepid", "Journey", "Lancer", "Magnum", "Mayfair", "Mirada", "Monaco", "Neon", "Nitro", "Omni", "Polara", "Raider", "RAM", "Ramcharger", "RAM Van", "Shadow", "Spirit", "Stealth", "Stratus", "Super Bee", "Viper", "WC series"],
  ["DONGFENG"]: ["370", "580", "A30", "A9", "Aeolus AX7 Plus", "Aeolus E70", "Aeolus Haohan", "Aeolus Haoji", "Aeolus L7", "Aeolus L8", "Aeolus Yixuan", "Aeolus Yixuan Max", "AX4", "AX7", "Box", "C36", "DF6", "DFSK 500", "DFSK ix5", "DFSK ix7", "E11K", "EC36", "Fengon 500", "Fengon 560", "Fengon E5", "Fengon ix5", "Fengon ix7", "Fengon Mini EV", "Fukang ES600", "H30 Cross", "Huge", "Mage", "Mengshi M-Hero 800", "Mengshi M-Hero 817", "Mengshi M-Hero 917", "MPV", "Nammi 01", "Nammi 06", "Nano EX1", "Oting", "Paladin", "Rich", "Rich 7", "S30", "Shine", "Shine GS", "Shine Max", "Sky EV01", "Aeolus Yixuan GS", "Z9"],
  ["DONINVEST"]: ["Assol", "Kondor", "Orion", "Orion M"],
  ["DONKERVOORT"]: ["D8", "D8 Cosworth", "D8 GT", "D8 GTO", "D8 Zetec", "F22", "P24 RS"],
  ["DR"]: ["1.0", "3.0", "5.0", "6.0", "7.0", "PK8"],
  ["DS"]: ["3", "3 Crossback", "4", "5", "7 Crossback", "9", "No4", "No7", "No8"],
  ["DW_HOWER"]: ["H3", "H5"],
  ["EAGLE"]: ["Premier", "Summit", "Talon", "Vision", "Vista"],
  ["EAGLE_CARS"]: ["SS"],
  ["EDSEL"]: ["Ranger"],
  ["ENOVATE"]: ["ME5", "ME7"],
  ["EONYX"]: ["City (M2)"],
  ["ESTEO"]: ["Exlantix ES", "Exlantix ET", "MX"],
  ["EVERUS"]: ["VE-1"],
  ["EVOLUTE"]: ["i-JET", "i-JOY", "i-PRO", "i-SKY", "i-SPACE", "i-VAN"],
  ["EXCALIBUR"]: ["Series IV", "Series V"],
  ["E_CAR"]: ["GD04B"],
  ["E_MOBIL"]: ["Ё-Кроссовер"],
  ["FACEL_VEGA"]: ["FV"],
  ["FAW"]: ["Bestune B70", "Bestune B70S", "Bestune E01", "Bestune Joyee 03", "Bestune Joyee 07", "Bestune Joyee 08", "Bestune M9", "Bestune NAT", "Bestune Pony", "Bestune T33", "Bestune T55", "Bestune T77", "Bestune T90", "Bestune T99", "Bestune Yueyi 03", "Bestune Yueyi 07", "Besturn B30", "Besturn B50", "Besturn B70", "Besturn X40", "CA6420", "D60", "Jinn", "Oley", "V2", "V5", "Vita", "Besturn X80"],
  ["FERRARI"]: ["12Cilindri", "208/308", "250 GT/E 2+2", "250 GTO", "250 GT Berlinetta", "288 GTO", "296", "328", "330 GT 2+2", "348", "360", "365 GTB/4 Daytona", "365 GTC", "400", "412", "456", "458", "488", "512 M", "512 BB", "512 TR", "550", "575M", "599", "612", "812", "849 Testarossa", "Amalfi", "California", "Daytona SP3", "Dino 206 GT", "Dino 208/308 GT4", "Dino 246 GT", "Enzo", "F12", "F355", "F40", "F430", "F50", "F80", "F8", "FF", "FXX K", "GTC4Lusso", "LaFerrari", "Luce", "Mondial", "Monza SP", "Portofino", "Purosangue", "Roma", "SC40", "SF90", "Testarossa"],
  ["FIAT"]: ["1100", "124", "124 Spider", "124 Sport Spider", "125", "126", "127", "128", "130", "131", "132", "1500", "2300", "238", "500", "500L", "500X", "508", "600", "600e", "850", "900T", "Albea", "Argenta", "Barchetta", "Brava", "Bravo", "Cinquecento", "Coupe", "Croma", "Doblo", "Duna", "Egea", "Fastback", "Fiorino", "Freemont", "Fullback", "Grande Panda", "Idea", "Linea", "Marea", "Multipla", "Palio", "Panda", "Pulse", "Punto", "Qubo", "Regata", "Ritmo", "Scudo", "Sedici", "Seicento", "Siena", "Stilo", "Strada", "Tempra", "Tipo", "Topolino", "Ulysse", "Uno", "X 1/9"],
  ["FISKER"]: ["Karma", "Ocean"],
  ["FLANKER"]: ["F"],
  ["FORD"]: ["300", "Aerostar", "Anglia", "Aspire", "Bronco", "Bronco Basecamp", "Bronco-II", "Bronco Sport", "B-MAX", "Capri", "Consul", "Contour", "Cortina", "Cougar", "Country Squire", "Crestline", "Crown Victoria", "Custom", "C-MAX", "Econoline", "Econovan", "EcoSport", "Edge", "Equator", "Equator Sport", "Escape", "Escort", "Escort (North America)", "Everest", "Evos", "Excursion", "Expedition", "Explorer", "Explorer EV", "Explorer Sport Trac", "Fairlane", "Fairmont", "Falcon", "Festiva", "Fiesta", "Fiesta ST", "Figo", "Five Hundred", "Flex", "Focus", "Focus RS", "Focus ST", "Freda", "Freestar", "Freestyle", "Fusion", "Fusion (North America)", "F-100", "F-150", "F-2", "Galaxie", "Galaxy", "GPA", "Granada", "Granada (North America)", "GT", "GT40", "Ikon", "Ixion", "KA", "Kuga", "Laser", "LTD", "LTD Country Squire", "LTD Crown Victoria", "M151", "Mainline", "Maverick", "Model A", "Model T", "Mondeo", "Mondeo ST", "Mustang", "Mustang Mach-E", "Orion", "Probe", "Puma", "Puma ST", "Ranchero", "Ranger", "Ranger (North America)", "Scorpio", "Sierra", "Spectron", "S-MAX", "Taunus", "Taurus", "Taurus X", "Telstar", "Tempo", "Territory", "Thunderbird", "Torino", "Tourneo Connect", "Tourneo Courier", "Tourneo Custom", "Transit", "Transit Connect", "Transit Custom", "V8", "Windstar", "Zephyr"],
  ["FORTHING"]: ["CM7", "Friday", "Lingzhi M5", "Lingzhi Plus", "M7", "T5", "T5L", "T5 EVO", "Thunder", "U-Tour M4", "V9", "Xinghai S7", "Yacht"],
  ["FOTON"]: ["Conqueror 5", "Mars 7", "Mars 9", "Midi", "Sauvana", "Tunland", "Tunland F9", "Tunland G7", "Tunland G9", "Tunland V7", "Tunland V9"],
  ["FRANKLIN"]: ["Series 15"],
  ["FSO"]: ["125p", "126p", "127p", "132p", "Lanos", "Polonez", "Warszawa"],
  ["FSR"]: ["Tarpan"],
  ["FUQI"]: ["6500 (Land King)"],
  ["GAC"]: ["Aion V", "Empow", "GN8", "GS3", "GS4", "GS5", "GS8", "Hyptec HT", "iA5", "M8", "S7", "S9"],
  ["GAZ"]: ["12 ЗИМ", "13 «Чайка»", "14 «Чайка»", "18", "21 «Волга»", "22 «Волга»", "2308 «Атаман»", "2330 «Тигр»", "24 «Волга»", "25", "3102 «Волга»", "31022 «Волга»", "310221 «Волга»", "31029 «Волга»", "3103 «Волга»", "3105 «Волга»", "3110 «Волга»", "31105 «Волга»", "3111 «Волга»", "46", "61", "64", "ГАЗ 67", "69", "А", "М1", "М-20 «Победа»", "М-72", "Volga Siber"],
  ["GEELY"]: ["Atlas", "Atlas Pro", "Azkarra", "Beauty Leopard", "Binrui", "Binrui Cool", "Binyue", "Binyue Cool", "Binyue L", "Boyue", "Boyue Cool", "Boyue L", "Boyue Pro", "Boyue REV", "Cityray", "CK (Otaka)", "Coolray", "Cowboy", "Emgrand", "Emgrand 7", "Emgrand EC8", "Emgrand EC7", "Emgrand GL", "Emgrand GT", "Emgrand L", "Emgrand S", "Emgrand X7", "EX2", "EX5", "EX5 EM-i", "Galaxy A7", "Galaxy E5", "Galaxy E8", "Galaxy L6", "Galaxy L7", "Galaxy LEVC L380", "Galaxy M7", "Galaxy M9", "Galaxy Starshine 6", "Galaxy Starshine 7", "Galaxy Starshine 8", "Galaxy Starship 7", "Galaxy TT", "Galaxy V900", "GC5", "GC6", "GC7", "GC9", "Geometry A", "Geometry C", "Geometry E", "Geometry G6", "Geometry M6", "Geome Xingyuan", "GS", "GX3 Pro", "Haoqing", "Haoyue", "Haoyue L", "Haoyue Pro", "Farizon Happiness", "Icon", "Jiaji", "Kandi EX3", "LC (Panda)", "LC (Panda) Cross", "MK", "MK Cross", "Monjaro", "MR", "Okavango", "Panda", "Preface", "Radar King Kong", "SC7", "Tugella", "TX4", "FC (Vision)", "Vision S1", "Vision X3", "Vision X3 Pro", "Vision X6", "Vision X6 Pro", "Xingyue", "Xingyue L", "Farizon FX"],
  ["GENESIS"]: ["G70", "G80", "G90", "GV60", "GV70", "GV80", "GV80 Coupe"],
  ["GEO"]: ["Metro", "Prizm", "Spectrum", "Storm", "Tracker"],
  ["GMA"]: ["T.33", "T.50"],
  ["GMC"]: ["100", "Acadia", "Canyon", "C/K", "Envoy", "Hummer EV", "Jimmy", "Safari", "Savana", "Sierra", "Sonoma", "Suburban", "Syclone", "Terrain", "Typhoon", "Vandura", "Yukon"],
  ["GOGGOMOBIL"]: ["T", "TS"],
  ["GONOW"]: ["Aoosed G5", "GX6", "Troy"],
  ["GORDON"]: ["Roadster"],
  ["GP"]: ["Madison"],
  ["GREAT_WALL"]: ["Coolbear", "Cowry (V80)", "Deer", "Florid", "Hover H3", "Hover H5", "Hover H6", "Hover", "Hover M1 (Peri 4x4)", "Hover M2", "Hover M4", "Hover Pi", "Pegasus", "Peri", "Poer", "Poer King Kong", "Safe", "Sailor", "Shanhai Poer", "Sing RUV", "Socool", "Voleex C10 (Phenom)", "Voleex C30", "Voleex C50", "Wingle 7", "Wingle"],
  ["GUMPERT"]: ["Apollo"],
  ["HAFEI"]: ["Brio", "Minyi", "Princip", "Saibao", "Sigma", "Simbo"],
  ["HAIMA"]: ["2", "3", "6P", "7", "7X", "8S", "Aishang EV", "E3", "Family", "Family F7", "Freema", "M3", "S5", "S5 Young"],
  ["HANOMAG"]: ["Rekord", "Typ 13"],
  ["HANTENG"]: ["X7"],
  ["HAVAL"]: ["Chitu", "DaGou (Big Dog)", "Dargo", "F5", "F7", "F7x", "H1", "H10", "H2", "H2s", "H3", "H4", "H5", "H6", "H6L", "H6S", "H6 Coupe", "H7", "H8", "H9", "Jolion", "KuGou", "M6", "Menglong (Raptor)", "Shenshou", "Xiaolong", "Xiaolong Max"],
  ["HAWTAI"]: ["Boliger", "B21", "Laville"],
  ["HEDMOS"]: ["06"],
  ["HEINKEL"]: ["Typ 154"],
  ["HENGTIAN"]: ["L4600"],
  ["HENNESSEY"]: ["Venom F5", "Venom GT"],
  ["HINDUSTAN"]: ["Ambassador", "Contessa"],
  ["HIPHI"]: ["X", "Y", "Z"],
  ["HISPANO_SUIZA"]: ["K6"],
  ["HOLDEN"]: ["Apollo", "Astra", "Barina", "Calais", "Caprice", "Commodore", "Cruze", "Frontera", "Jackaroo", "Monaro", "Rodeo", "Statesman", "UTE", "Vectra", "Zafira"],
  ["HONDA"]: ["145", "Accord", "Acty", "Airwave", "Ascot", "Ascot Innova", "Avancier", "Ballade", "Beat", "Breeze", "Brio", "Capa", "City", "Civic", "Civic Ferio", "Civic Type R", "Concerto", "Crider", "Crossroad", "Crosstour", "CR-V", "CR-X", "CR-Z", "Domani", "e", "Edix", "Element", "Elevate", "Elysion", "Envix", "e:NP1", "e:NP2", "e:NS1", "e:NS2", "e:Ny1", "Clarity", "Fit", "Fit Aria", "Fit Shuttle", "Freed", "FR-V", "Grace", "Horizon", "HR-V", "Insight", "Inspire", "Integra", "Integra SJ", "Jade", "Jazz", "Lagreat", "Legend", "Life", "Logo", "MDX", "Mobilio", "Mobilio Spike", "N360", "NSX", "N-BOX", "N-BOX+", "N-BOX Slash", "N-One", "N-VAN", "N-WGN", "Odyssey", "Odyssey (North America)", "Orthia", "Partner", "Passport", "Pilot", "Prelude", "Prologue", "Quint", "Rafaga", "Ridgeline", "S2000", "S500", "S600", "S660", "Saber", "Shuttle", "Stepwgn", "Stream", "Street", "Super-One", "S-MX", "That'S", "Today", "Torneo", "UR-V", "Vamos", "Vezel", "Vigor", "WR-V", "XR-V", "Ye P7", "Ye S7", "Z", "Zest", "ZR-V"],
  ["HONGQI"]: ["EH7", "E-HS3", "E-HS7", "E-HS9", "E-QM5", "H5", "H6", "H7", "H9", "HQ9", "HS3", "HS5", "HS6", "HS7", "Guoya", "L5", "LS7", "Tiangong 05", "Tiangong 06", "Tiangong 08"],
  ["HORCH"]: ["830", "853", "901"],
  ["HOZON"]: ["Neta Aya", "Neta GT", "Neta L", "Neta S", "Neta U", "Neta U-II", "Neta V", "Neta X"],
  ["HSV"]: ["Maloo"],
  ["HUAIHAI_HOANN"]: ["EK01"],
  ["HUANGHAI"]: ["Antelope", "Landscape", "N1", "N2", "N7", "Plutus"],
  ["HUAZI"]: ["Omega"],
  ["HUDSON"]: ["Custom Eight", "Deluxe Eight", "Hornet", "Super Six"],
  ["HUMBER"]: ["Hawk"],
  ["HUMMER"]: ["H1", "H2", "H3"],
  ["HYCAN"]: ["007", "A06", "V09", "Z03"],
  ["HYPERION"]: ["XP-1"],
  ["HYUNDAI"]: ["Accent", "Alcazar", "Aslan", "Atos", "Avante", "Avante N", "Azera", "Bayon", "Casper", "Celesta", "Centennial", "Click", "Coupe", "Creta", "Custin", "Custo", "Dynasty", "Elantra", "Elantra N", "Elexio", "Encino", "Entourage", "EON", "Equus", "Excel", "Exter", "Galloper", "Genesis", "Genesis Coupe", "Getz", "Grace", "Grandeur", "Grand Starex", "H200", "HB20", "H-1", "i10", "i20", "i20 N", "i30", "i30 N", "i40", "Inster", "IONIQ", "IONIQ 3", "IONIQ 5", "IONIQ 5 N", "IONIQ 6", "IONIQ 9", "ix20", "ix25", "ix35", "ix55", "Kona", "Kona N", "Lafesta", "Lantra", "Lavita", "Marcia", "Matrix", "Maxcruz", "Mistra", "Mufasa", "Nexo", "Palisade", "Pony", "Reina", "Santamo", "Santa Cruz", "Santa Fe", "Santro", "Scoupe", "Solaris", "Sonata", "Starex", "Stargazer", "Staria", "Stellar", "Terracan", "Tiburon", "Trajet", "Tucson", "Tuscani", "Veloster", "Venue", "Veracruz", "Verna", "XG"],
  ["ICAR"]: ["03", "V23", "V27"],
  ["ICAUR"]: ["V27"],
  ["IG"]: ["2125 «Комби»", "2126 «Ода»", "21261 «Фабула»", "2715", "2717", "27175", "Москвич-412"],
  ["IM_MOTORS"]: ["L6", "L7", "LS6", "LS7", "LS8", "LS9"],
  ["INEOS"]: ["Grenadier"],
  ["INFINITI"]: ["ESQ", "EX", "FX", "G", "I", "J", "JX", "M", "Q", "Q30", "Q40", "Q50", "Q60", "Q70", "QX30", "QX4", "QX50", "QX55", "QX56", "QX60", "QX65", "QX70", "QX80"],
  ["INNOCENTI"]: ["Elba", "Mille", "Mini"],
  ["INTERNATIONAL"]: ["Scout", "Travelall"],
  ["INVICTA"]: ["S1"],
  ["IRAN_KHODRO"]: ["Arisun", "Dena", "Paykan", "Runna", "Sahra", "Samand", "Sarir", "Soren", "Tara"],
  ["ISDERA"]: ["Commendatore 112i", "Imperator 108i", "Spyder"],
  ["ISUZU"]: ["117", "Amigo", "Ascender", "Aska", "Axiom", "Bellett", "Bighorn", "D-Max", "Fargo", "Fargo Filly", "Florian", "Gemini", "Hombre", "Impulse", "KB", "Lingtuo", "Midi", "MU", "MU-7", "MU-X", "Oasis", "Pa Nero", "Piazza", "Rodeo", "Ruimai", "Stylus", "T17", "T30 Explorer", "TF (Pickup)", "Trooper", "VehiCross", "Wizard"],
  ["IVECO"]: ["Massif"],
  ["JAC"]: ["A5", "E30X", "Hunter", "iEV7L", "iEV7S", "iEVA50", "iEVS4", "J2 (Yueyue)", "J3 (Tongyue,Tojoy)", "J4 (Heyue A30)", "J5 (Heyue)", "J6 (Heyue RS)", "J7", "J7 (Binyue)", "Jiayue X7", "JS2", "JS2 Pro", "JS3", "JS4", "JS5", "JS6", "JS9", "M4", "M5", "M1 (Refine)", "Refine L6 Max", "Refine M3", "Refine RF8", "RF8", "S1 (Rein)", "S3 Pro", "S4", "S5 (Eagle)", "S6", "S7", "Sehol A5 Plus", "Sehol Aipao", "Sehol E20X", "Sehol X6", "Sehol X8", "Sehol X8 Plus", "S2", "S3", "T6", "T8", "T8 Pro", "T9", "Yttrium 3"],
  ["JAECOO"]: ["EJ6", "J6", "J7", "J8"],
  ["JAGUAR"]: ["E-Pace", "E-type", "F-Pace", "F-Type", "I-Pace", "Mark 2", "Mark IX", "S-Type", "XE", "XF", "XFR", "XJ", "XJ220", "XJR", "XJS", "XK", "XKR", "X-Type"],
  ["JEEP"]: ["Avenger", "Cherokee", "CJ", "Comanche", "Commander", "Compass", "Gladiator", "Grand Cherokee", "Grand Commander", "Wagoneer", "Liberty (North America)", "Liberty (Patriot)", "Recon", "Renegade", "Wagoneer S", "Wrangler"],
  ["JELAND"]: ["C5", "J6", "J7", "J8"],
  ["JENSEN"]: ["Interceptor", "S-V8"],
  ["JETOUR"]: ["DASHING", "Freedom", "G700", "Reaolo", "Shanhai L6", "Shanhai L7", "Shanhai L7 Plus", "Shanhai L9", "Shanhai T1", "Shanhai T2", "T1", "T2", "Traveller", "X50", "X70", "X70L", "X70+", "X70 Pro", "X90", "X90+", "X90 Pro", "X95"],
  ["JETTA"]: ["VA3", "VA7", "VS5", "VS7", "VS8"],
  ["JIANGNAN"]: ["Chuanqi"],
  ["JIDU"]: ["01", "07"],
  ["JINBEI"]: ["Haise", "Haise S"],
  ["JMC"]: ["Baodian", "Dadao", "Vigus", "Vigus Work", "Yuhu 7"],
  ["JMEV"]: ["01", "EV3", "GSE (Yi)"],
  ["JONWAY"]: ["UFO A380"],
  ["KAIYI"]: ["E5", "Shiyue", "X3", "X3 Pro", "X7 Kunlun"],
  ["KANONIR"]: ["2317"],
  ["KARMA"]: ["Revero", "Revero GT"],
  ["KAWEI"]: ["K1", "K150", "K150GT"],
  ["KGM"]: ["Actyon", "Korando", "Musso", "Musso Sports", "Rexton", "Rexton Sports", "Tivoli", "Torres"],
  ["KIA"]: ["Avella", "Borrego", "Cachet", "Cadenza", "Capital", "Carens", "Carnival", "Carstar", "Ceed", "Ceed GT", "Cerato", "Clarus", "Concord", "Elan", "Enterprise", "EV2", "EV3", "EV4", "EV5", "EV6", "EV9", "Forte", "Joice", "K3", "K4", "K5", "K7", "K8", "K9", "K900", "KX1", "KX3", "KX5", "KX7", "Lotze", "Magentis", "Mentor", "Mohave", "Morning", "Niro", "Opirus", "Optima", "Pegas", "Picanto", "Potentia", "Pregio", "Pride", "Proceed", "PV5", "Quanlima", "Quoris", "Ray", "Retona", "Rio", "Sedona", "Seltos", "Sephia", "Shuma", "Soluto", "Sonet", "Sorento", "Soul", "Soul EV", "Spectra", "Sportage", "Sportage (China)", "Stinger", "Stonic", "Syros", "Tasman", "Telluride", "Towner", "Venga", "Visto", "XCeed", "X-Trek"],
  ["KNEWSTAR"]: ["001"],
  ["KOENIGSEGG"]: ["Agera", "CC850", "CC8S", "CCR", "CCX", "Gemera", "Jesko", "One:1", "Regera"],
  ["KOMBAT"]: ["Т98"],
  ["KTM"]: ["X-Bow"],
  ["KYC"]: ["F3"],
  ["LAMBORGHINI"]: ["350/400 GT", "Aventador", "Centenario", "Countach", "Countach LPI 800-4", "Diablo", "Egoista", "Espada", "Fenomeno", "Gallardo", "Huracán", "Islero", "Jalpa", "Jarama", "LM001", "LM002", "Miura", "Murcielago", "Reventon", "Revuelto", "Sesto Elemento", "Sián", "Silhouette", "Temerario", "Urraco", "Urus", "Veneno"],
  ["LANCIA"]: ["Appia", "Aurelia", "A 112", "Beta", "Dedra", "Delta", "Flaminia", "Flavia", "Fulvia", "Gamma", "Hyena", "Kappa", "Lambda", "Lybra", "Monte Carlo", "Musa", "Phedra", "Prisma", "Rally 037", "Stratos", "Thema", "Thesis", "Trevi", "Voyager", "Y10", "Ypsilon", "Zeta"],
  ["LANDWIND"]: ["Fashion (CV9)", "Forward", "Х9", "X5", "X6", "X7"],
  ["LAND_ROVER"]: ["Defender", "Discovery", "Discovery Sport", "Range Rover Evoque", "Freelander", "Range Rover", "Range Rover Sport", "Range Rover Velar", "Series I", "Series II", "Series III"],
  ["LEAPMOTOR"]: ["A05", "A10", "B01", "B05 (Lafa 5)", "B10", "C01", "C10", "C11", "C16", "D19", "D99", "S01", "T03"],
  ["LETIN"]: ["Mengo", "Mengo Pro"],
  ["LEVC"]: ["L380", "TX"],
  ["LEXUS"]: ["CT", "ES", "GS", "GS F", "GX", "HS", "IS", "IS F", "LBX", "LC", "LFA", "LM", "LS", "LX", "NX", "RC", "RC F", "RX", "RZ", "SC", "TX", "TZ", "UX"],
  ["LIEBAO"]: ["Leopard"],
  ["LIFAN"]: ["650 EV", "Breez (520)", "Cebrium (720)", "Celliya (530)", "Murman (820)", "Myway", "Smily", "Solano", "X50", "X60", "X70"],
  ["LIGIER"]: ["JS 51"],
  ["LINCOLN"]: ["Aviator", "Blackwood", "Capri", "Continental", "Continental Mark", "Corsair", "LS", "Mark LT", "Mark VII", "Mark VIII", "MKC", "MKS", "MKT", "MKX", "MKZ", "Nautilus", "Navigator", "Premiere", "Town Car", "Versailles", "Z", "Zephyr"],
  ["LINGXI"]: ["L"],
  ["LIVAN"]: ["7", "8", "9", "Blue Baloon", "S6 Pro", "X3 Pro", "X6 Pro"],
  ["LIXIANG"]: ["i6", "i8", "L6", "L7", "L8", "L9", "Mega", "One"],
  ["LOGEM"]: ["EC30"],
  ["LOTUS"]: ["2-Eleven", "340R", "3-Eleven", "Eclat", "Elan", "Eletre", "Elise", "Elite", "Emeya", "Emira", "Esprit", "Europa", "Europa S", "Evija", "Evora", "Excel", "Exige", "For Me"],
  ["LTI"]: ["FX4", "TX"],
  ["LUAZ"]: ["1302 Волынь", "967", "969"],
  ["LUCID"]: ["Air", "Gravity"],
  ["LUXEED"]: ["R7", "RX", "S7", "V9"],
  ["LUXGEN"]: ["Luxgen7 MPV", "Luxgen7 SUV", "Luxgen5", "U6 Turbo", "U7 Turbo"],
  ["LYNK_CO"]: ["01", "02", "03", "05", "06", "07", "08", "09", "10", "900", "Z10", "Z20"],
  ["MAEXTRO"]: ["S800", "V680", "V800"],
  ["MAHINDRA"]: ["Armada", "Bolero", "CJ-3", "CL", "Commander", "Marshal", "MM", "NC 640 DP", "Scorpio", "Thar", "Verito", "Voyager", "Xylo"],
  ["MAPLE"]: ["30X", "X3 Pro"],
  ["MARCOS"]: ["GTS", "LM 400", "LM 500", "Mantis", "Marcasite"],
  ["MARLIN"]: ["5EXi", "Sportster"],
  ["MARUSSIA"]: ["B1", "B2"],
  ["MARUTI"]: ["1000", "800", "Alto", "Baleno", "Esteem", "Gypsy", "Omni", "Versa", "Wagon R", "Zen"],
  ["MASERATI"]: ["228", "3200 GT", "3500 GT", "420", "4200 GT", "Barchetta Stradale", "Biturbo", "Bora", "Chubasco", "Ghibli", "GranCabrio", "GranTurismo", "Grecale", "GT2 Stradale", "Indy", "Karif", "Khamsin", "Kyalami", "Levante", "MC12", "MC20", "MCPura", "Merak", "Mexico", "Mostro Zagato", "Quattroporte", "Royale", "Shamal"],
  ["MATRA"]: ["Murena"],
  ["MAXUS"]: ["D60", "D90", "EUNIQ 5", "EUNIQ 6", "G10", "G20", "G50", "G50 Max", "G50 Plus", "G70", "G90", "Interstellar", "MIFA 5", "MIFA 7", "MIFA 9", "T70", "T90", "Territory", "V70"],
  ["MAYBACH"]: ["57", "62", "Exelero", "SW38"],
  ["MAZDA"]: ["1000", "121", "1300", "2", "3", "323", "3 MPS", "5", "6", "616", "626", "6e", "6 MPS", "818", "929", "Atenza", "Autozam AZ-1", "Autozam AZ-3", "Autozam Clef", "Axela", "AZ-Offroad", "AZ-Wagon", "Biante", "Bongo", "Bongo Friendee", "BT-50", "B-series", "Capella", "Carol", "Chantez", "Cosmo", "Cronos", "CX-90", "CX-3", "CX-30", "CX-4", "CX-5", "CX-50", "CX-60", "CX-6e", "CX-7", "CX-70", "CX-8", "CX-80", "CX-9", "Demio", "Efini MS-6", "Efini MS-8", "Efini MS-9", "Etude", "Eunos 100", "Eunos 300", "Eunos 500", "Eunos 800", "Eunos Cosmo", "Eunos Presso", "EZ-6", "EZ-60", "E-Series", "Familia", "Flair", "Flair Crossover", "Flair Wagon", "Lantis", "Laputa", "Luce", "Millenia", "MPV", "MX-3", "MX-30", "MX-5", "MX-6", "Navajo", "Persona", "Premacy", "Proceed", "Proceed Levante", "Proceed Marvie", "Protege", "Revue", "Roadster", "RX-4", "RX-5", "RX-7", "RX-8", "R360", "Savanna RX-7", "Scrum", "Sentia", "Spiano", "Tribute", "Verisa", "Xedos 6", "Xedos 9"],
  ["MCLAREN"]: ["MP4-12C", "540C", "570GT", "570S", "600LT", "650S", "675LT", "720S", "750S", "765LT", "Artura", "Elva", "F1", "GT", "GTS", "P1", "Senna", "W1"],
  ["MEGA"]: ["Club", "Monte Carlo", "Track"],
  ["MERCEDES"]: ["190 SL", "220 (W187)", "300 SLR", "GLC Coupe AMG", "AMG GT", "AMG GT 4-Door Coupe", "AMG ONE", "AMG PureSpeed", "A-Класс", "A-Класс AMG", "B-Класс", "Citan", "CLA", "CLA AMG", "CLC-Класс", "CLE", "CLE AMG", "CLK AMG GTR", "CLK-Класс", "CLK-Класс AMG", "CLS", "CLS AMG", "CL-Класс", "CL-Класс AMG", "C-Класс", "C-Класс AMG", "EQA", "EQB", "EQC", "EQE", "EQE AMG", "EQE SUV", "EQE SUV AMG", "EQS", "EQS AMG", "EQS SUV", "EQT", "EQV", "E-Класс", "E-Класс AMG", "GLA", "GLA AMG", "GLB AMG", "GLB", "GLC Coupe", "GLC", "GLC AMG", "GLE", "GLE AMG", "GLE Coupe", "GLE Coupe AMG", "GLK-Класс", "GLS", "GLS AMG", "GL-Класс", "GL-Класс AMG", "G-Класс", "G-Класс AMG", "G-Класс AMG 6x6", "Marco Polo", "Maybach EQS SUV", "Maybach GLS", "Maybach G 650 Landaulet", "Maybach SL", "Metris", "M-Класс", "M-Класс AMG", "R-Класс", "R-Класс AMG", "Simplex", "SLC", "SLC AMG", "SLK-Класс", "SLK-Класс AMG", "SLR McLaren", "SLS AMG", "SL-Класс", "SL-Класс AMG", "Maybach S-Класс", "S-Класс", "S-Класс AMG", "Typ 630", "T-Класс", "Vaneo", "Viano", "Vito", "VLE", "V-Класс", "W100", "W105", "W108", "W110", "W111", "W114", "W115", "W120", "W121", "W123", "W124", "W128", "W136", "W138", "W142", "W180", "W186", "W188", "W189", "W191", "190 (W201)", "W21", "W29", "X-Класс"],
  ["MERCURY"]: ["Capri", "Colony Park", "Cougar", "Eight", "Grand Marquis", "Marauder", "Mariner", "Marquis", "Milan", "Montego", "Monterey", "Mountaineer", "Mystique", "Sable", "Topaz", "Tracer", "Villager"],
  ["MERKUR"]: ["XR4Ti"],
  ["MESSERSCHMITT"]: ["KR200"],
  ["METROCAB"]: ["Metrocab I", "Metrocab II (TTT)"],
  ["MG"]: ["07", "3", "350", "4X", "4 EV", "5", "550", "5 EV", "5 Scorpio", "6", "6 Pro", "7", "750", "8", "Cyberster", "ES5", "F", "GS", "HS", "Maestro", "Metro", "MGA", "MGB", "Midget", "Montego", "Mulan", "One", "Pilot", "RV8", "RX5", "RX8", "RX9", "T60", "TD Midget", "TF", "U9", "Xpower SV", "ZR", "ZS", "ZT"],
  ["MIA"]: ["Electric"],
  ["MICRO"]: ["Microlino"],
  ["MICROCAR"]: ["F8C", "M8", "MC", "M.Go", "Virgo"],
  ["MINELLI"]: ["TF 1800"],
  ["MINI"]: ["Aceman", "Cabrio", "Clubman", "Countryman", "Coupe", "Hatch", "Paceman", "Roadster"],
  ["MITSUBISHI"]: ["3000 GT", "500", "Airtrek", "Aspire", "ASX", "Attrage", "Bravo", "Carisma", "Celeste", "Challenger", "Chariot", "Colt", "Cordia", "Debonair", "Delica", "Delica D:2", "Delica D:3", "Delica D:5", "Delica Mini", "Destinator", "Diamante", "Dignity", "Dingo", "Dion", "Eclipse", "Eclipse Cross", "eK Active", "eK Classic", "eK Custom", "eK Space", "eK Sport", "eK Wagon", "eK X", "Emeraude", "Endeavor", "Eterna", "Freeca", "FTO", "Galant", "Galant Fortis", "Grandis", "GTO", "i", "i-MiEV", "Jeep J", "L200", "L300", "L400", "Lancer", "Lancer Cargo", "Lancer Evolution", "Lancer Ralliart", "Legnum", "Libero", "Minica", "Minicab", "Mirage", "Montero", "Montero Sport", "Outlander", "Outlander Sport", "Pajero", "Pajero iO", "Pajero Junior", "Pajero Mini", "Pajero Pinin", "Pajero Sport", "Pistachio", "Proudia", "Raider", "RVR", "Sapporo", "Savrin", "Sigma", "Space Gear", "Space Runner", "Space Star", "Space Wagon", "Starion", "Strada", "Toppo", "Town Box", "Tredia", "Triton", "Xforce", "Xpander"],
  ["MITSUOKA"]: ["Bubu Classic SSK", "Buddy", "Galue", "Galue 204", "Himiko", "Le-Seyde", "Like", "M55", "MC-1", "Nouera", "Orochi", "Ray", "Rock Star", "Ryoga", "Ryugi", "Viewt", "Yuga", "Zero 1"],
  ["MOBILIZE"]: ["Limo"],
  ["MORGAN"]: ["3 Wheeler", "4/4", "4 Seater", "AeroMax", "Aero 8", "Aero Coupe", "Aero SuperSports", "Plus 4", "Plus 8", "Plus Six", "Roadster", "Supersport"],
  ["MORRIS"]: ["Eight", "Marina"],
  ["MOSCVICH"]: ["2136", "2137", "2138", "2140", "2141", "2142", "3", "3е", "400", "401", "402", "403", "407", "408", "410", "411", "412", "423", "424", "426", "427", "430", "434П", "5", "6", "8", "Дуэт", "Иван Калита", "Князь Владимир", "М70", "М90", "Святогор", "Юрий Долгорукий"],
  ["M_HERO"]: ["I"],
  ["NASH"]: ["Ambassador"],
  ["NIO"]: ["EC6", "EC7", "EL6", "ES6", "ES7", "ES8", "ES9", "ET5", "ET7", "ET9", "Firefly", "Onvo L60", "Onvo L80", "Onvo L90"],
  ["NISSAN"]: ["100NX", "180SX", "200SX", "240SX", "280ZX", "300ZX", "350Z", "370Z", "AD", "Almera", "Almera Classic", "Almera Tino", "Altima", "Ariya", "Armada", "Auster", "Autech Zagato Stelvio AZ1", "Avenir", "Bassara", "BE-1", "Bluebird", "Bluebird Maxima", "Bluebird Sylphy", "Caravan", "Cedric", "Cefiro", "Cherry", "Cima", "NV100 Clipper", "Clipper Rio", "Crew", "Cube", "Datsun", "Dayz", "Dayz Roox", "Dualis", "Elgrand", "Exa", "Expert", "Fairlady Z", "Figaro", "Frontier", "Frontier Pro", "Fuga", "Gloria", "Gravite", "GT-R", "Homy", "Hypermini", "Juke", "Juke Nismo", "Kait", "Kicks", "Kix", "Kubistar", "Lafesta", "Langley", "Lannia", "Largo", "Latio", "Laurel", "Laurel Spirit", "Leaf", "Leopard", "Liberta Villa", "Liberty", "Livina", "Lucino", "Magnite", "March", "Maxima", "Micra", "Mistral", "Moco", "Murano", "N6", "N7", "Navara (Frontier)", "Note", "NP200", "NP300", "NV200", "NV300", "NV350 Caravan", "NX8", "NX Coupe", "Otti", "Pao", "Pathfinder", "Patrol", "Pino", "Pixo", "Prairie", "Presage", "Presea", "President", "Primastar", "Primera", "Pulsar", "Qashqai", "Qashqai+2", "Quest", "Rasheen", "R'nessa", "Rogue", "Rogue Sport", "Roox", "Safari", "Sakura", "Sentra", "Serena", "Silvia", "Skyline", "Skyline Crossover", "Stagea", "Stanza", "Sunny", "Sylphy", "S-Cargo", "Teana", "Terra", "Terrano", "Terrano Regulus", "Tiida", "Tino", "Titan", "Urvan", "Vanette", "Versa", "Versa Note", "Wingroad", "Xterra", "X-Terra", "X-Trail", "Z"],
  ["NOBLE"]: ["M12 GTO", "M15", "M600"],
  ["NORDCROSS"]: ["001"],
  ["OLDSMOBILE"]: ["442", "Achieva", "Alero", "Aurora", "Bravada", "Custom Cruiser", "Cutlass", "Cutlass Calais", "Cutlass Ciera", "Cutlass Supreme", "Delta 88", "Eighty-Eight", "Firenza", "Intrigue", "Ninety-Eight", "Omega", "Series 60", "Series 70", "Silhouette", "Starfire", "Toronado", "Vista Cruiser"],
  ["OLTCIT"]: ["Club"],
  ["OMODA"]: ["C5", "C7", "C9", "E5", "S5", "S5 GT"],
  ["OPEL"]: ["4/8 PS", "Adam", "Admiral", "Agila", "Ampera", "Antara", "Ascona", "Astra", "Astra OPC", "Calibra", "Campo", "Cascada", "Combo", "Commodore", "Corsa", "Corsa OPC", "Crossland X", "Diplomat", "Frontera", "Grandland", "GT", "Insignia", "Insignia OPC", "Kadett", "Kapitan", "Karl", "Lotus Omega", "Manta", "Meriva", "Meriva OPC", "Mokka", "Monterey", "Monza", "Olympia", "Omega", "P4", "Rekord", "Rocks Electric", "Senator", "Signum", "Sintra", "Speedster", "Super Six", "Tigra", "Vectra", "Vectra OPC", "Vita", "Vivaro", "Zafira", "Zafira Life", "Zafira OPC"],
  ["ORA"]: ["03", "5", "7", "Ballet Cat", "Black Cat", "Good Cat", "iQ", "Lightning Cat", "SAR (Saloon) Mecha Dragon", "White Cat"],
  ["ORANGE"]: ["01"],
  ["OSCA"]: ["2500 GT"],
  ["OSHAN"]: ["COS1", "Cosmos", "X5", "X5 Plus", "X7", "X7 Plus", "Z6"],
  ["OTING"]: ["Paladin", "Palasso", "Rich 7", "Z9"],
  ["OVERLAND"]: ["Roadster"],
  ["PACKARD"]: ["200/250", "Caribbean", "Clipper", "Custom Eight", "One-Ten", "One-Twenty", "Six", "Super Eight", "Twelve"],
  ["PAGANI"]: ["Huayra", "Utopia", "Zonda"],
  ["PANOZ"]: ["Esperante", "Roadster"],
  ["PERODUA"]: ["Alza", "Kancil", "Kelisa", "Kembara", "Kenari", "MyVi", "Nautica", "Traz", "Viva"],
  ["PEUGEOT"]: ["1007", "104", "106", "107", "108", "2008", "201", "202", "203", "204", "205", "205 GTi", "206", "207", "207i (Iran Khodro)", "208", "208 GTi", "3008", "301", "304", "305", "306", "307", "308", "308 GTi", "309", "4007", "4008", "402", "403", "404", "405", "406", "407", "408", "5008", "504", "505", "508", "604", "605", "607", "806", "807", "Bipper", "Expert", "iOn", "Landtrek", "Partner", "Pick Up", "RCZ", "Rifter", "Traveller"],
  ["PGO"]: ["Cevennes", "Hemera", "Speedster II"],
  ["PIAGGIO"]: ["Porter"],
  ["PIERCE_ARROW"]: ["Twelve"],
  ["PLYMOUTH"]: ["Acclaim", "Barracuda", "Breeze", "Caravelle", "Colt Vista", "Cranbrook", "De Luxe", "Fury", "Gran Fury", "Horizon", "Laser", "Neon", "Prowler", "Reliant", "Road Runner", "Satellite", "Sundance", "Turismo", "Valiant", "Volare", "Voyager"],
  ["POLAR_STONE_JISHI"]: ["01"],
  ["POLESTAR"]: ["1", "2", "3", "4", "5"],
  ["PONTIAC"]: ["6000", "Aztek", "Bonneville", "Catalina", "Fiero", "Firebird", "Firefly", "G4", "G5", "G6", "G8", "Grand AM", "Grand Prix", "GTO", "Laurentian", "LeMans", "Montana", "Parisienne", "Phoenix", "Solstice", "Sunbird", "Sunfire", "Sunrunner", "Tempest", "Torpedo", "Torrent", "Trans Sport", "Vibe", "Wave"],
  ["PORSCHE"]: ["356", "718 Spyder", "911", "911 GT1", "911 GT2", "911 GT3", "911 R", "911 S/T", "912", "914", "918 Spyder", "924", "928", "944", "959", "968", "Boxster", "Carrera GT", "Cayenne", "Cayman", "Cayman GT4", "Macan", "Panamera", "Taycan"],
  ["PREMIER"]: ["118NE", "Padmini"],
  ["PROMO_AUTO"]: ["Багги Type 1", "Драгстер", "Дрифт-кар", "Формула", "GT & Touring", "Хот-род и Кастом", "Offroad", "Спортпрототип", "Rally/cross", "Самоделки", "Shortcut"],
  ["PROTON"]: ["Arena", "Exora", "Gen-2", "Inspira", "Iriz", "Juara", "Perdana", "Persona", "Preve", "Putra", "Saga", "Satria", "Savvy", "Tiara", "Waja", "Wira (400 Series)", "X50", "X70"],
  ["PUCH"]: ["G-modell", "Pinzgauer"],
  ["PUMA"]: ["GTB", "GTE"],
  ["PUNK"]: ["Duoduo"],
  ["QIANTU"]: ["K50"],
  ["QINGLING"]: ["Taga H"],
  ["QOROS"]: ["3", "5"],
  ["QVALE"]: ["Mangusta"],
  ["RADAR"]: ["RD6"],
  ["RADFORD"]: ["Type 62-2"],
  ["RAM"]: ["1500", "Dakota", "ProMaster City", "Rampage", "V1000"],
  ["RAVON"]: ["Gentra", "Matiz", "Nexia R3", "R2", "R4"],
  ["RAYTON_FISSORE"]: ["Magnum"],
  ["RELIANT"]: ["Scimitar Sabre"],
  ["RENAISSANCE_CARS"]: ["Tropica Roadster"],
  ["RENAULT"]: ["10", "11", "12", "14", "15", "16", "17", "18", "19", "20", "21", "25", "30", "4", "4CV", "5", "6", "8", "9", "Alaskan", "Arkana", "Austral", "Avantime", "Boreal", "Captur", "Caravelle", "Celtaquatre", "City K-ZE", "Clio", "Clio RS", "Symbol", "Clio V6", "Dauphine", "Dokker", "Duster", "Espace", "Express", "Filante", "Floride", "Fluence", "Fregate", "Fuego", "Grand Koleos", "Kadjar", "Kangoo", "Kaptur", "Kardian", "Kiger", "Koleos", "KWID", "Laguna", "Latitude", "Lodgy", "Logan", "Lutecia", "Megane", "Megane E-Tech", "Megane RS", "Modus", "QM6", "Rafale", "Rapid", "Rodeo", "Safrane", "Sandero", "Sandero RS", "Scenic", "Sport Spider", "Symbioz", "Taliant", "Talisman", "Trafic", "Triber", "Twingo", "Twizy", "Type NN", "Vel Satis", "Vivastella", "Wind", "ZOE"],
  ["REZVANI"]: ["Arsenal", "Beast", "Fortress", "Tank"],
  ["RIMAC"]: ["Concept_One", "C Two", "Nevera"],
  ["RINSPEED"]: ["Chopster"],
  ["RISING_AUTO"]: ["F7", "Marvel R", "R7"],
  ["RIVIAN"]: ["R1S", "R1T", "R2"],
  ["ROEWE"]: ["750", "Clever", "D6", "D7", "E50", "i5", "i6", "i6 Max", "iMAX8", "M7", "Marvel X", "RX3", "RX3 Pro", "RX5", "RX5 Max", "RX8", "RX9", "Whale"],
  ["ROLLS_ROYCE"]: ["20", "20/25", "Boat Tail", "Camargue", "Corniche", "Cullinan", "Dawn", "Ghost", "Park Ward", "Phantom", "Silver Cloud", "Silver Ghost", "Silver Seraph", "Silver Shadow", "Silver Spirit", "Silver Spur", "Silver Wraith", "Spectre", "Wraith"],
  ["RONART"]: ["Lightning"],
  ["ROSSA"]: ["Concept"],
  ["ROVER"]: ["100", "14", "200", "25", "400", "45", "600", "75", "800", "Maestro", "Metro", "Mini", "Montego", "P3", "P4", "P6", "SD1", "Streetwise"],
  ["ROX"]: ["01", "Adamas"],
  ["RUSSO_BALTIQUE"]: ["С24"],
  ["SAAB"]: ["600", "90", "900", "9000", "93", "95", "96", "99", "9-2X", "9-3", "9-4X", "9-5", "9-7X", "Sonett"],
  ["SAIC"]: ["H5", "Z7"],
  ["SAIPA"]: ["Quick", "Saina", "Shahin", "Tiba"],
  ["SALEEN"]: ["S7", "S281"],
  ["SAMSUNG"]: ["QM3", "QM5", "QM6", "SM3", "SM5", "SM6", "SM7", "XM3"],
  ["SANDSTORM"]: ["Alreem", "S24"],
  ["SANTANA"]: ["PS-10"],
  ["SATURN"]: ["Astra", "Aura", "ION", "LS", "LW", "Outlook", "Relay", "SC", "Sky", "SL", "SW", "VUE"],
  ["SCION"]: ["FR-S", "iA", "iM", "iQ", "tC", "xA", "xB", "xD"],
  ["SCOUT"]: ["Terra", "Traveler"],
  ["SEARS"]: ["Model J"],
  ["SEAT"]: ["132", "133", "Alhambra", "Altea", "Arona", "Arosa", "Ateca", "Cordoba", "Exeo", "Fura", "Ibiza", "Ibiza Cupra", "Inca", "Leon", "Leon Cupra", "Malaga", "Marbella", "Mii", "Ronda", "Tarraco", "Toledo"],
  ["SENAT"]: ["1000", "900"],
  ["SERES"]: ["M5", "M7", "M9", "SF5"],
  ["SHANGHAI_MAPLE"]: ["C31", "C32", "C51", "C52", "C61", "C81"],
  ["SHUANGHUAN"]: ["Noble", "Sceo"],
  ["SIMCA"]: ["1300/1500", "1307"],
  ["SKM"]: ["M7"],
  ["SKODA"]: ["100 Series", "105, 120", "1200", "440", "445", "Citigo", "Elroq", "Elroq RS", "Enyaq", "Enyaq Coupe", "Enyaq Coupe RS", "Enyaq RS", "Epiq", "Fabia", "Fabia RS", "Favorit", "Felicia", "Forman", "Kamiq", "Karoq", "Kodiaq", "Kodiaq GT", "Kodiaq RS", "Kushaq", "Kylaq", "Octavia", "Octavia RS", "Peaq", "Popular", "Rapid", "Roomster", "Scala", "Slavia", "Superb", "Yeti"],
  ["SKYWELL"]: ["ET5", "HT-i"],
  ["SKYWORTH"]: ["EV6"],
  ["SMART"]: ["Forfour", "Fortwo", "#1", "#3", "#5", "#6", "Roadster"],
  ["SMZ"]: ["С-1Л", "С-3А", "С-3Д", "С-3Л"],
  ["SOLARIS"]: ["HC", "HS", "KRS", "KRX"],
  ["SOLLERS"]: ["SF1", "SP7", "ST6", "ST8", "ST9"],
  ["SOUEAST"]: ["A5", "DX3", "DX5", "DX7", "DX8", "DX8S", "Lioncel", "S06", "S07", "S09", "Soveran", "V3", "V5", "V6 Cross"],
  ["SPECTRE"]: ["R42"],
  ["SPYKER"]: ["C12", "C8"],
  ["SSANG_YONG"]: ["Actyon", "Actyon Sports", "Chairman", "Istana", "Kallista", "Korando", "Korando Family", "Korando Sports", "Korando Turismo", "Kyron", "Musso", "Nomad", "Rexton", "Rexton Sports", "Rodius", "Stavic", "Tivoli", "XLV", "Torres"],
  ["START"]: ["1963-1968"],
  ["STELATO"]: ["G9", "S9"],
  ["STEYR"]: ["1500", "Haflinger"],
  ["STUDEBAKER"]: ["Golden Hawk"],
  ["SUBARU"]: ["1000", "360", "Alcyone", "Ascent", "Tribeca", "Baja", "Bighorn", "Bistro", "Brat", "BRZ", "Chiffon", "Crosstrek", "Dex", "Dias Wagon", "Domingo", "Exiga", "E-Outback", "Forester", "Getaway", "Impreza", "Impreza WRX", "Impreza WRX STi", "Justy", "Legacy", "Legacy Lancaster", "Leone", "Levorg", "Libero", "Lucra", "Outback", "Pleo", "Pleo Plus", "R1", "R2", "Rex", "Sambar", "Solterra", "Stella", "SVX", "Trailseeker", "Traviq", "Trezia", "Uncharted", "Vivio", "WRX", "WRX STi", "XT", "XV"],
  ["SUZUKI"]: ["Across", "Aerio", "Alto", "Alto Lapin", "APV", "Baleno", "Beidouxing", "Cappuccino", "Cara", "Carry", "Celerio", "Cervo", "Ciaz", "Cultus", "DZire", "Eeco", "Equator", "Ertiga", "Escudo", "Esteem", "Every", "e Vitara", "Forenza", "Fronte", "Fronx", "Grand Vitara", "Hustler", "Ignis", "Invicto", "Jimny", "Kei", "Kizashi", "Landy", "Liana", "Mighty Boy", "MR Wagon", "Palette", "Reno", "Samurai", "Sidekick", "Solio", "Spacia", "Splash", "Swace", "Swift", "SX4", "S-Presso", "Twin", "Verona", "Victoris", "Vitara", "Wagon R", "Wagon R+", "Wagon R Smile", "Xbee", "XL7", "X-90"],
  ["SWM"]: ["G01", "G01F", "G03F", "G05", "G05 Pro", "Tiger", "X3", "Shineray X30", "X7"],
  ["TAGAZ"]: ["Aquila", "C10", "C190", "C-30", "Vega", "Road Partner", "Tager"],
  ["TALBOT"]: ["1510", "Avenger", "Horizon", "Rancho", "Samba", "Solara", "Tagora"],
  ["TANK"]: ["300", "400", "500", "700"],
  ["TATA"]: ["Aria", "Curvv", "Estate", "Indica", "Indigo", "Nano", "Safari", "Sierra", "Sumo", "Sumo Grande", "Telcoline", "Xenon"],
  ["TATRA"]: ["57", "77", "80", "87", "T600", "T603", "T613", "T700"],
  ["TAZZARI"]: ["Zero"],
  ["TENET"]: ["T4", "T4L", "T7", "T8"],
  ["TENET_PLUS"]: ["L6"],
  ["TESLA"]: ["Cybertruck", "Model 3", "Model S", "Model X", "Model Y", "Roadster"],
  ["THAIRUNG"]: ["Transformer"],
  ["THINK"]: ["City"],
  ["TIANMA"]: ["Century", "Dragon"],
  ["TIANYE"]: ["Admiral"],
  ["TOFAS"]: ["Kartal", "Murat 124", "Murat 131", "Sahin", "Serce"],
  ["TOYOTA"]: ["2000GT", "4Runner", "Agya", "Allex", "Allion", "Alphard", "Altezza", "Aqua", "Aristo", "Aurion", "Auris", "Avalon", "Avanza", "Avensis", "Avensis Verso", "Aygo", "Aygo X", "bB", "Belta", "Blade", "Blizzard", "Brevis", "bZ", "bZ3", "bZ3C", "bZ3X", "bZ4X", "bZ5", "bZ7", "Caldina", "Cami", "Camry", "Camry Solara", "Carina", "Carina E", "Carina ED", "Cavalier", "Celica", "Celsior", "Century", "Chaser", "Classic", "Comfort", "COMS", "Copen", "Corolla", "Corolla Cross", "Corolla II", "Corolla Levin", "Corolla Rumion", "Corolla Spacio", "Corolla Verso", "Corona", "Corona EXiV", "Corsa", "Cressida", "Cresta", "Crown", "Crown Kluger", "Crown Majesta", "Curren", "Cynos", "C-HR", "C-HR+", "Duet", "Echo", "Esquire", "Estima", "Etios", "FJ Cruiser", "Fortuner", "Frontlander", "FunCargo", "Gaia", "GR86", "Grand HiAce", "Grand Highlander", "Granvia", "GR GT", "GT86", "Harrier", "HiAce", "Highlander", "Hilux", "Hilux Champ", "Hilux Surf", "Innova", "Ipsum", "iQ", "ISis", "Ist", "Izoa", "JPN Taxi", "Kluger", "Land Cruiser", "Land Cruiser FJ", "Land Cruiser Prado", "Levin", "Lite Ace", "Mark II", "Mark X", "Mark X ZiO", "MasterAce Surf", "Matrix", "Mega Cruiser", "Mirai", "Model F", "MR2", "MR-S", "Nadia", "Noah", "Opa", "Origin", "Paseo", "Passo", "Passo Sette", "Picnic", "Pixis Epoch", "Pixis Joy", "Pixis Mega", "Pixis Space", "Pixis Van", "Platz", "Porte", "Premio", "Previa", "Prius", "Prius v (+)", "Prius Alpha", "Prius c", "ProAce", "ProAce City", "Probox", "Progres", "Pronard", "Publica", "Ractis", "Raize", "Raum", "RAV4", "Regius", "RegiusAce", "Reiz", "Roomy", "Rumion", "Rush", "Sai", "Scepter", "Sequoia", "Sera", "Sienna", "Sienta", "Soarer", "Soluna", "Spade", "Sparky", "Sports 800", "Sprinter", "Sprinter Carib", "Sprinter Marino", "Sprinter Trueno", "Starlet", "Starlet Cross", "Succeed", "Supra", "Tacoma", "Tank", "Tercel", "Touring HiAce", "Town Ace", "Tundra", "Urban Cruiser", "Urban Cruiser Taisor", "Vanguard", "Vellfire", "Veloz", "Venza", "Verossa", "Verso", "Verso-S", "Vios", "Vista", "Vitz", "Voltz", "Voxy", "Wigo", "Wildlander", "WiLL", "WiLL Cypha", "Windom", "Wish", "xA", "Yaris", "Yaris Cross", "Yaris Verso", "Zelas"],
  ["TRABANT"]: ["1.1", "600", "P 601", "P50"],
  ["TRAMONTANA"]: ["Tramontana"],
  ["TRIUMPH"]: ["Acclaim", "GT6", "Spitfire", "Stag", "TR3", "TR4", "TR6", "TR7", "TR8"],
  ["TRUMPCHI"]: ["E8", "E9", "Emkoo", "Empow", "ES9", "GA4", "GA4 Plus", "GA6", "GA8", "GE3", "GM6", "GM8", "GS3", "GS3 Power", "GS4", "GS4 Max", "GS4 Plus", "GS5", "GS8", "M6", "M6 Max", "M6 Pro", "M8", "S7", "S9"],
  ["TVR"]: ["280", "350", "390", "400", "420", "450", "Cerbera", "Chimaera", "Griffith", "Sagaris", "S-Series", "Taimar", "Tamora", "Tasmin", "Tuscan"],
  ["UAZ"]: ["3151", "3153", "3159", "3160", "3162 Simbir", "469", "Астеро", "Hunter", "Patriot", "Pickup"],
  ["ULTIMA"]: ["Can-Am", "GTR", "RS"],
  ["UMO"]: ["5", "8"],
  ["VAUXHALL"]: ["Adam", "Ampera", "Astra", "Carlton", "Cavalier", "Chevette", "Combo", "Corsa", "Firenza", "Frontera", "Insignia", "Lotus Carlton", "Meriva", "Mokka", "Monaro", "Omega", "Royale", "Tigra", "Vectra", "Velox", "Ventora", "Viceroy", "Victor", "Viva", "Vivaro", "VXR8", "Zafira"],
  ["VAZ"]: ["1111 Ока", "2101", "2102", "2103", "2104", "2105", "2106", "2107", "2108", "2109", "21099", "2110", "2111", "2112", "2113", "2114", "2115", "2120 Надежда", "2121 (4x4)", "2123", "2129", "2131 (4x4)", "Priora", "2328", "2329", "Aura", "Azimut", "EL Lada", "e-Largus", "Granta", "Iskra", "Kalina", "Largus", "Niva", "Niva Legend", "Niva Travel", "Revolution", "Vesta", "XRAY", "X-cross 5"],
  ["VECTOR"]: ["M12", "W8 Twin Turbo"],
  ["VENTURI"]: ["210", "260 LM", "300 Atlantique", "400 GT"],
  ["VENUCIA"]: ["D60", "D60 Plus", "Т60", "VX6", "V-Online"],
  ["VGV"]: ["Bolden", "U70", "U70 Pro", "U75 Plus", "VX7"],
  ["VINFAST"]: ["LUX A2.0", "LUX SA2.0", "VF6", "VF7", "VF8", "VF9"],
  ["VOLGA"]: ["C50", "K40", "K50"],
  ["VOLKSWAGEN"]: ["181", "Amarok", "Arteon", "Arteon R", "Atlas", "Atlas Cross Sport", "Beetle", "Bora", "Caddy", "California", "Caravelle", "Corrado", "C-Trek", "Derby", "Eos", "EuroVan", "Fox", "Gol", "Golf", "Golf Country", "Golf GTI", "Golf Plus", "Golf R", "Golf R32", "Golf Sportsvan", "ID.3", "ID.4", "ID.5", "ID.6", "ID.7", "ID.Buzz", "ID.Era 8X", "ID.Era 9X", "ID.Unyx", "ID.Unyx 06", "ID.Unyx 07", "ID.Unyx 08", "ID. Polo", "Iltis", "Jetta", "K70", "Karmann-Ghia", "Lamando", "Lavida", "Lavida XR", "Lupo", "Lupo GTI", "Magotan", "Multivan", "Parati", "Passat", "Passat CC", "Passat (North America and China)", "Phaeton", "Phideon", "Pointer", "Polo", "Polo GTI", "Polo R WRC", "Quantum", "Rabbit", "Routan", "Sagitar", "Santana", "Scirocco", "Scirocco R", "Sharan", "SpaceFox", "SP-2", "Tacqua", "Taigo", "Taigun", "Talagon", "Taos", "Taro", "Tavendor", "Tayron", "Teramont", "Tharu", "Tharu XR", "Tiguan", "Tiguan R", "Touareg", "Touareg R", "Touran", "Transporter", "Type 1", "Type 166", "Type 2", "Type 3", "Type 4", "Type 82", "T-Cross", "T-Roc", "T-Roc R", "up!", "Vento", "Viloran", "Voyage", "XL1"],
  ["VOLVO"]: ["120 Series", "140 Series", "164", "240 Series", "260 Series", "300 Series", "440", "460", "480", "66", "740", "760", "780", "850", "940", "960", "C30", "C40", "C70", "EC40", "EM90", "ES90", "EX30", "EX30 Cross Country", "EX40", "EX60", "EX90", "Laplander", "P1800", "P1900", "PV444", "PV544", "S40", "S60", "S60 Cross Country", "S70", "S80", "S90", "V40", "V40 Cross Country", "V50", "V60", "V60 Cross Country", "V70", "V90", "V90 Cross Country", "XC40", "XC60", "XC70", "XC90"],
  ["VORTEX"]: ["Corda", "Estina", "Tingo"],
  ["VOYAH"]: ["Courage", "Dream", "Free", "Passion", "Passion S", "Taishan", "Taishan X8"],
  ["VUHL"]: ["05"],
  ["WANDERER"]: ["W22", "W23", "W26", "W50"],
  ["WARTBURG"]: ["1.3", "353"],
  ["WELTMEISTER"]: ["E5", "EX5", "EX6 Plus", "W6"],
  ["WESTFIELD"]: ["SEiGHT", "SEi & Sport"],
  ["WEY"]: ["05", "07", "80", "Coffee 01", "Gaoshan (High Mountain)", "Lanshan (Blue Mountain)", "Latte", "Macchiato", "Mocca", "V9X", "VV5", "VV6", "VV7"],
  ["WIESMANN"]: ["GT", "Roadster"],
  ["WILLIS"]: ["CJ", "Jeepster", "MB", "Knight Model 20"],
  ["WULING"]: ["Aishang A100C", "Binguo", "Binguo Pro", "Binguo S", "Hongguang", "Hongguang Plus", "Hongguang S", "Hongguang V", "Huajing S", "Jiachen", "Mini EV", "Nano EV", "Nebula", "Starlight", "Starlight 560", "Starlight 730", "Starlight L", "Starlight S", "Star Asta", "Sunshine", "Victory", "Xingchi", "Zhiguan EV"],
  ["W_MOTORS"]: ["Fenyr Supersport", "Lykan Hypersport"],
  ["XCITE"]: ["X-Cross 7", "X-Cross 8"],
  ["XEV"]: ["Yoyo"],
  ["XIAOMI"]: ["SU7", "YU7"],
  ["XINKAI"]: ["Pickup X3", "SR-V X3", "SUV X3"],
  ["XPENG"]: ["G3", "G6", "G7", "G9", "GX", "Mona L03", "Mona M03", "P5", "P7", "P7i", "P7+", "X9"],
  ["YANDEX_ROVER"]: ["R3"],
  ["YEMA"]: ["EC30", "Spica", "T70"],
  ["YIPAI"]: ["007", "008", "M8", "Nammi 01", "Nammi 06"],
  ["YUDO"]: ["Yuntu"],
  ["YULON"]: ["Feeling"],
  ["ZASTAVA"]: ["10", "Florida", "Skala", "Yugo"],
  ["ZAZ"]: ["965", "966", "968", "Chance", "1105 «Дана»", "Forza", "Sens", "1103 «Славута»", "1102 «Таврия»", "Vida", "Lanos"],
  ["ZEEKR"]: ["001", "007", "009", "7X", "8X", "9X", "Mix", "X"],
  ["ZENOS"]: ["E10"],
  ["ZENVO"]: ["Aurora", "ST1", "TSR-S"],
  ["ZHIDO"]: ["Rainbow"],
  ["ZIBAR"]: ["MK2"],
  ["ZIL"]: ["111", "114", "117", "4104"],
  ["ZIS"]: ["101", "102", "110"],
  ["ZOTYE"]: ["Coupa", "Domy X5", "Domy X7", "E200", "Nomad (RX6400)", "SR9", "T300", "T500", "T600", "T700", "T800", "Z100", "Z300"],
  ["ZUBR"]: ["Legenda", "Relikt", "Talisman", "Volat", "Zorka"],
  ["ZX"]: ["Admiral", "Grandlion", "Grand Tiger", "Landmark", "Terralord"],
};


// Build lookup structures at module load
const marksById = new Map<string, string>(MARKS_DATA.map(m => [m.id, m.name]));
const allModelNames: string[] = Object.values(MODELS_BY_MARK_ID).flat();

export const CAR_DATABASE: Record<string, string[]> = Object.fromEntries(
  MARKS_DATA
    .filter(m => MODELS_BY_MARK_ID[m.id])
    .map(m => [m.name, MODELS_BY_MARK_ID[m.id]])
);

export function getAllMarksWithIds(): Array<{ id: string; name: string }> {
  return MARKS_DATA;
}

export function getAllMakes(): string[] {
  return MARKS_DATA.map(m => m.name).sort((a, b) => a.localeCompare(b));
}

export function getModelsForMarkId(markId: string): string[] {
  return MODELS_BY_MARK_ID[markId] ?? [];
}

export function searchMakes(query: string): string[] {
  if (!query.trim()) return [];
  const q = query.toLowerCase();
  const starts: string[] = [], contains: string[] = [];
  for (const m of MARKS_DATA) {
    const n = m.name.toLowerCase();
    if (n.startsWith(q)) starts.push(m.name);
    else if (n.includes(q)) contains.push(m.name);
  }
  return [...starts, ...contains].slice(0, 12);
}

export function searchModels(query: string, confirmedMake?: string): string[] {
  if (!query.trim()) {
    if (confirmedMake) {
      const markId = MARKS_DATA.find(m => m.name === confirmedMake)?.id;
      return markId ? (MODELS_BY_MARK_ID[markId] ?? []).slice(0, 20) : [];
    }
    return [];
  }
  const q = query.toLowerCase();
  const source = confirmedMake
    ? (() => {
        const markId = MARKS_DATA.find(m => m.name === confirmedMake)?.id;
        return markId ? (MODELS_BY_MARK_ID[markId] ?? []) : allModelNames;
      })()
    : allModelNames;
  const starts: string[] = [], contains: string[] = [];
  for (const model of source) {
    const m = model.toLowerCase();
    if (m.startsWith(q)) starts.push(model);
    else if (m.includes(q)) contains.push(model);
  }
  return [...new Set([...starts, ...contains])].slice(0, 15);
}
